i18n = require "i18n"
require "common.gg.gg"
require "common.gg.game"
require "common.gg.hotfix"
require "common.gg.dbmgr"
require "common.gg.openui"
require "common.gg.Event"
require "common.gg.loginserver"
require "common.gg.CompositeComponent"
require "common.gg.ClusterQueue"
require "common.gg.ServiceMgr"
require "common.gg.ShareMgr"
require "common.gg.ShareProxy"
require "common.gg.PlayerProxy"
