constant.MAIL_TYPE_SYS = 0 --""
constant.MAIL_TYPE_PLY = 1 --""

constant.MAIL_DURATION = 30 * 24 --""

constant.MAIL_ATTACH_RES = 0 --""
constant.MAIL_ATTACH_ITEM = 1 --""

constant.MAIL_GET_FILTER_ALL = 0 --""
constant.MAIL_GET_FILTER_BEFORE = 1 --""
constant.MAIL_GET_FILTER_AFTER = 2 --""

constant.MAIL_GET_FILTER_DESC = {
    [constant.MAIL_GET_FILTER_ALL] = "all player",
    [constant.MAIL_GET_FILTER_BEFORE] = "before the mail sending time",
    [constant.MAIL_GET_FILTER_AFTER] = "after the mail sending time",
}

constant.MAIL_ATTACH_RES_COUNT_LIMMIT = 2147483647 --""

constant.MAIL_TEMPLATE_NEW_PLAYER = 10000 --""
constant.MAIL_TEMPLATE_RECHARGE_NOTIFICATION = 10001  --""
constant.MAIL_TEMPLATE_RECHARGE_GIFT_NOTIFICATION = 10002  --""
constant.MAIL_TEMPLATE_UNION_HY_SHARE = 20001 --""
constant.MAIL_TEMPLATE_UNION_WEEK_RANK = 20002 --""
constant.MAIL_TEMPLATE_UNION_RANK = 20003 --""
constant.MAIL_TEMPLATE_OTH_UNION_HY_SHARE = 20004 --""
constant.MAIL_TEMPLATE_OTH_UNION_RANK = 20005 --""
constant.MAIL_TEMPLATE_UNION_POS_HY_SHARE = 20006 --""_""_""
constant.MAIL_TEMPLATE_UNION_POS_HY_RANK = 20007 --""_""_""
constant.MAIL_TEMPLATE_UNION_HY_COMBATVAL = 20008 --""_""_""_""
constant.MAIL_TEMPLATE_UNION_WEEK_RANK_COMBATVAL = 20009 --""_""_""_""
constant.MAIL_TEMPLATE_OTH_UNION_HY_COMBATVAL = 20010 --""_""_""_""
constant.MAIL_TEMPLATE_OTH_UNION_RANK_COMBATVAL = 20011 --""_""_""_""
constant.MAIL_TEMPLATE_STARMAP_UNION_REWARD = 20012 --""

constant.MAIL_TEMPLATE_COMPLETE_MINTS = 20101 --nft""
constant.MAIL_TEMPLATE_INCOMPLETE_MINTS = 20102 --nft""
constant.MAIL_TEMPLATE_ACTPVPRANK = 30001 --""pvp""
constant.MAIL_TEMPLATE_ACTSTARMAPUNION = 30002 --""pvp""
constant.MAIL_TEMPLATE_ACTSTARMAPFIRSTGET = 30003 --""
constant.MAIL_TEMPLATE_REBATETOINVITER = 40002 --""
constant.MAIL_TEMPLATE_SENDMAILTOINVITER = 40001 --""
constant.MOON_REWARD_MAIL_TEMPLATE = 40003   -- ""
constant.MAIL_TEMPLATE_COMPENSATION = 40004   --  ""
constant.MAIL_TEMPLATE_TRANGE_REBATETOINVITER = 40005 --""
constant.MAIL_SYS_SENDNAME = "Galaxy Blitz Team"

constant.MAIL_TEMPLATE_PVP_RANK = 50001   --  pvp""
constant.MAIL_TEMPLATE_PVP_STAGE = 50002   --  pvp""
constant.MAIL_TEMPLATE_PVP_MATCH_REWARD = 50003   --  pvp""

constant.MAIL_TEST_ACTIVITY_NEW_REG_REWARD = 500000
constant.MAIL_TEST_ACTIVITY_DAY_REWARD = 500000
constant.MAIL_TEST_ACTIVITY_MIT_HOLDER_REWARD = 500000

constant.MAIL_TEMPLATE_LEVEL_GIF_PACK = 30004 --""
constant.STARPACK_REWARD_MAIL_TEMPLATE = 50004   -- ""