
constant.TASK_WARSHIP_LV = 101            --""x""
constant.TASK_WARSHIP_SKILL_LV = 102      --""x""
constant.TASK_WARSHIP_LVUP = 103      --""x""
constant.TASK_WARSHIP_SKILL_LVUP = 104    --""x""
constant.TASK_HERO_LV = 201               --""x""
constant.TASK_HERO_SKILL_LV = 202         --""x""
constant.TASK_HERO_SWITCH_SKILL = 203     --""
constant.TASK_HERO_LVUP = 204         --""x""
constant.TASK_HERO_SKILL_LVUP = 205       --""x""
constant.TASK_ARMY_ADD_HERO = 206       --""x""
constant.TASK_SANCTURARY_ADD_HERO = 207  -- ""x""
constant.TASK_BUILD_LV_COUNT = 301        --""X""Y""Z""
constant.TASK_BUILD_LVUP_COUNT = 302      --""x""
constant.TASK_TRAIN_SOLIDERS = 401        --""x""y""
constant.TASK_LVUP_SOLIDERS = 403        --""x""
constant.TASK_TRAIN_RESERVE_ARMY = 404        --""x""
constant.TASK_SOLDIER_JOIN_BATTLE = 405        --""x""y""
constant.TASK_SOLDIER_LV = 406        --y""x
constant.TASK_RESERVE_ARMY_TRAIN = 410   --""x""
constant.TASK_PVP_COUNT = 601             --Pvp""x
constant.TASK_PVP_SCORE = 602             --Pvp""x
constant.TASK_PVE_WIN = 611               --PVE""x""
constant.TASK_DESTORY_BUILD_TYPE_COUNT = 621  --""x""y""
constant.TASK_DESTORY_BUILD_COUNT = 624       --""x""y""
constant.TASK_COLLECT_RES_COUNT = 701         --""x""
constant.TASK_COLLECT_RES_NUM = 702           --""x""y""
constant.TASK_CONSUME_RES_NUM = 712           --""x""y""
constant.TASK_JION_GUILD = 801                --""
constant.TASK_DONATE_IN_GUILD  = 802            -- ""x""
constant.TASK_STARMAP_ATTACK  = 803             --""x""
constant.TASK_CHANGE_NAME = 901               --""
constant.TASK_SPEEDUP_COUNT = 902             --""x""
constant.TASK_REPAIR_COUNT = 903              --""
constant.TASK_CASHOUT_COUNT = 904             --""x""
constant.TASK_DAILY_LOGIN = 905             --""
constant.TASK_DRAW_CARD = 906             --""x""y""（y""0，""）
constant.TASK_TARGET_KEYS = {
    [constant.TASK_WARSHIP_LV] = "WarshipLv",            --""x""
    [constant.TASK_WARSHIP_SKILL_LV] = "WarshipSkillLv",      --""x""
    [constant.TASK_WARSHIP_LVUP] = "WarshipLvUp",      --""x""
    [constant.TASK_WARSHIP_SKILL_LVUP] = "WarshipSkillLvUp",      --""x""
    [constant.TASK_HERO_LV] = "HeroLv",               --""x""
    [constant.TASK_HERO_SKILL_LV] = "HeroSkillLv",         --""x""
    [constant.TASK_HERO_SWITCH_SKILL] = "HeroSwitchSkill",     --""
    [constant.TASK_HERO_LVUP] = "HeroLvUp",         --""x""
    [constant.TASK_HERO_SKILL_LVUP] = "HeroSkillLvUp",         --""x""
    [constant.TASK_BUILD_LV_COUNT] = "BuildLvCount",        --""X""Y""Z""
    [constant.TASK_BUILD_LVUP_COUNT] = "BuildLvUpCount",        --""x""
    [constant.TASK_TRAIN_SOLIDERS] = "TrainSoliders",        --""x""y""
    [constant.TASK_LVUP_SOLIDERS] = "LvUpSoliders",        --""x""
    [constant.TASK_RESERVE_ARMY_TRAIN] = "ReserveArmyTrain", --""x""
    [constant.TASK_PVP_COUNT] = "PvpCount",             --Pvp""x
    [constant.TASK_PVP_SCORE] = "PvpScore",             --Pvp""x
    [constant.TASK_PVE_WIN] = "PveWin",               --PVE""x""
    [constant.TASK_DESTORY_BUILD_TYPE_COUNT] = "DestoryBuildTypeCount",  --""x""y""
    [constant.TASK_DESTORY_BUILD_COUNT] = "DestoryBuildCount",       --""x""y""
    [constant.TASK_COLLECT_RES_COUNT] = "CollectResCount",         --""x""
    [constant.TASK_COLLECT_RES_NUM] = "CollectResNum",           --""x""y""
    [constant.TASK_CONSUME_RES_NUM] = "ConsumeResNum",           --""x""y""
    [constant.TASK_JION_GUILD] = "JionGuild",                --""
    [constant.TASK_CHANGE_NAME] = "ChangeName",               --""
    [constant.TASK_SPEEDUP_COUNT] = "SpeedupCount",             --""x""
    [constant.TASK_REPAIR_COUNT] = "RepairCount",              --""
    [constant.TASK_CASHOUT_COUNT] = "CashoutCount",             --""x""
    [constant.TASK_DAILY_LOGIN] = "DailyLogin",             --""
    [constant.TASK_ARMY_ADD_HERO] = "ArmyAddHero",           --""x""
    [constant.TASK_SANCTURARY_ADD_HERO] = "SanAddHero",                --""x""
    [constant.TASK_TRAIN_RESERVE_ARMY] = "TrainReserve",               --""x""
    [constant.TASK_SOLDIER_JOIN_BATTLE] = "SoldierJoinBattle",             --""x""y""
    [constant.TASK_DONATE_IN_GUILD] = "DonateInGuild",              --""x""
    [constant.TASK_STARMAP_ATTACK] = "StarmapAtt",             --""x""
    [constant.TASK_DRAW_CARD] = "DrawCard",             --""x""y""（y""0，""）
    [constant.TASK_SOLDIER_LV] = "SoldierLv",            --y""x

}

constant.TASK_STATE = {     --""
    NONE = 0,       --""
    DONE = 1,       --""
    REWARD = 2,     --""
}

constant.TASK_TYPE = {   --""
    MAIN = 1,       --""
    BRANCH = 2,     --""
    DAILY = 3,      --""
}

--""
constant.TASK_TRAIN_NINJA = 22                      --""
constant.TASK_TRAIN_PARTICLE_GUNNER = 23            --""  
constant.TASK_TRAIN_ALIEN = 24                      --""allen""
constant.TASK_TRAIN_PARTICLE_TANK = 25              --""
constant.TASK_TRAIN_FIRE_ELEMENT = 26               --""
constant.TASK_TRAIN_SONIC_TANK = 27                 --""
constant.TASK_TRAIN_SIRIUS = 28                     --""
constant.TASK_TRAIN_ANTIMATTER = 29                 --""
constant.TASK_TRAIN_NUCLEAREXPLOSION = 30           --""
constant.TASK_TRAIN_SUICIDE_AIRCRAFT = 31           --""

