-- cfgKey                           string                           ""key
-- index                            int                              ""
-- name                             string                           ""
-- icon                             string                           ""
-- isPercent                        int                              "" 1:""100 2：""100
-- trueMul                          float                            ""（""）
-- mul                              float                            ""（""）
-- isTime                           int                              ""
-- isScientific                     int                              ""
-- count2Name                       json                             ""

return {
	["maxHp"] = {
		cfgKey = "maxHp",
		index = 1,
		name = "attri_maxHp",
		icon = "HP_icon",
		isPercent = 0,
		trueMul = nil,
		mul = nil,
		isTime = nil,
		isScientific = nil,
		count2Name = nil,
	},
	["atk"] = {
		cfgKey = "atk",
		index = 2,
		name = "attri_atk",
		icon = "ATK_icon",
		isPercent = 0,
		trueMul = nil,
		mul = 0.001,
		isTime = nil,
		isScientific = nil,
		count2Name = nil,
	},
	["moveSpeed"] = {
		cfgKey = "moveSpeed",
		index = 3,
		name = "attri_moveSpeed",
		icon = "Movement speed_icon",
		isPercent = 0,
		trueMul = nil,
		mul = nil,
		isTime = nil,
		isScientific = nil,
		count2Name = {
			[1] = {
				count = 2500,
				name = "moveSpeed_Slow",
			},
			[2] = {
				count = 4000,
				name = "moveSpeed_Moderate",
			},
			[3] = {
				count = 5500,
				name = "moveSpeed_Fast",
			},
			[4] = {
				count = 9999999999,
				name = "moveSpeed_Ultrafast",
			},
		},
	},
	["atkRange"] = {
		cfgKey = "atkRange",
		index = 4,
		name = "attri_atkRange",
		icon = "Range_icon",
		isPercent = 0,
		trueMul = nil,
		mul = nil,
		isTime = nil,
		isScientific = nil,
		count2Name = {
			[1] = {
				count = 3000,
				name = "atkRange_Short",
			},
			[2] = {
				count = 5000,
				name = "atkRange_Medium",
			},
			[3] = {
				count = 7000,
				name = "atkRange_Long",
			},
			[4] = {
				count = 9999999999,
				name = "atkRange_VeryLong",
			},
		},
	},
	["atkSpeed"] = {
		cfgKey = "atkSpeed",
		index = 5,
		name = "attri_atkSpeed",
		icon = "Attack speed_icon",
		isPercent = 0,
		trueMul = nil,
		mul = nil,
		isTime = nil,
		isScientific = nil,
		count2Name = nil,
	},
	["perMakeStarCoin"] = {
		cfgKey = "perMakeStarCoin",
		index = 6,
		name = "attri_perMakeStarCoin",
		icon = "icon_starcoin_50",
		isPercent = 0,
		trueMul = 0.001,
		mul = nil,
		isTime = nil,
		isScientific = 1,
		count2Name = nil,
	},
	["maxMakeStarCoin"] = {
		cfgKey = "maxMakeStarCoin",
		index = 7,
		name = "attri_maxMakeStarCoin",
		icon = "icon_starcoin_50",
		isPercent = 0,
		trueMul = 0.001,
		mul = nil,
		isTime = nil,
		isScientific = 1,
		count2Name = nil,
	},
	["perMakeIce"] = {
		cfgKey = "perMakeIce",
		index = 8,
		name = "attri_perMakeIce",
		icon = "icon_ice_50",
		isPercent = 0,
		trueMul = 0.001,
		mul = nil,
		isTime = nil,
		isScientific = 1,
		count2Name = nil,
	},
	["maxMakeIce"] = {
		cfgKey = "maxMakeIce",
		index = 9,
		name = "attri_maxMakeIce",
		icon = "icon_ice_50",
		isPercent = 0,
		trueMul = 0.001,
		mul = nil,
		isTime = nil,
		isScientific = 1,
		count2Name = nil,
	},
	["perMakeCarboxyl"] = {
		cfgKey = "perMakeCarboxyl",
		index = 10,
		name = "attri_perMakeCarboxyl",
		icon = "icon_hydroxyl_50",
		isPercent = 0,
		trueMul = 0.001,
		mul = nil,
		isTime = nil,
		isScientific = 1,
		count2Name = nil,
	},
	["maxMakeCarboxyl"] = {
		cfgKey = "maxMakeCarboxyl",
		index = 11,
		name = "attri_maxMakeCarboxyl",
		icon = "icon_hydroxyl_50",
		isPercent = 0,
		trueMul = 0.001,
		mul = nil,
		isTime = nil,
		isScientific = 1,
		count2Name = nil,
	},
	["perMakeTitanium"] = {
		cfgKey = "perMakeTitanium",
		index = 12,
		name = "attri_perMakeTitanium",
		icon = "icon_titanium_50",
		isPercent = 0,
		trueMul = 0.001,
		mul = nil,
		isTime = nil,
		isScientific = 1,
		count2Name = nil,
	},
	["maxMakeTitanium"] = {
		cfgKey = "maxMakeTitanium",
		index = 13,
		name = "attri_maxMakeTitanium",
		icon = "icon_titanium_50",
		isPercent = 0,
		trueMul = 0.001,
		mul = nil,
		isTime = nil,
		isScientific = 1,
		count2Name = nil,
	},
	["perMakeGas"] = {
		cfgKey = "perMakeGas",
		index = 14,
		name = "attri_perMakeGas",
		icon = "icon_gas_50",
		isPercent = 0,
		trueMul = 0.001,
		mul = nil,
		isTime = nil,
		isScientific = 1,
		count2Name = nil,
	},
	["maxMakeGas"] = {
		cfgKey = "maxMakeGas",
		index = 15,
		name = "attri_maxMakeGas",
		icon = "icon_gas_50",
		isPercent = 0,
		trueMul = 0.001,
		mul = nil,
		isTime = nil,
		isScientific = 1,
		count2Name = nil,
	},
	["storeStarCoin"] = {
		cfgKey = "storeStarCoin",
		index = 16,
		name = "attri_storeStarCoin",
		icon = "icon_starcoin_50",
		isPercent = 0,
		trueMul = 0.001,
		mul = nil,
		isTime = nil,
		isScientific = 1,
		count2Name = nil,
	},
	["storeIce"] = {
		cfgKey = "storeIce",
		index = 17,
		name = "attri_storeIce",
		icon = "icon_ice_50",
		isPercent = 0,
		trueMul = 0.001,
		mul = nil,
		isTime = nil,
		isScientific = 1,
		count2Name = nil,
	},
	["storeCarboxyl"] = {
		cfgKey = "storeCarboxyl",
		index = 18,
		name = "attri_storeCarboxyl",
		icon = "icon_hydroxyl_50",
		isPercent = 0,
		trueMul = 0.001,
		mul = nil,
		isTime = nil,
		isScientific = 1,
		count2Name = nil,
	},
	["storeTitanium"] = {
		cfgKey = "storeTitanium",
		index = 19,
		name = "attri_storeTitanium",
		icon = "icon_titanium_50",
		isPercent = 0,
		trueMul = 0.001,
		mul = nil,
		isTime = nil,
		isScientific = 1,
		count2Name = nil,
	},
	["storeGas"] = {
		cfgKey = "storeGas",
		index = 20,
		name = "attri_storeGas",
		icon = "icon_gas_50",
		isPercent = 0,
		trueMul = 0.001,
		mul = nil,
		isTime = nil,
		isScientific = 1,
		count2Name = nil,
	},
	["maxTrainSpace"] = {
		cfgKey = "maxTrainSpace",
		index = 21,
		name = "attri_maxTrainSpace",
		icon = "Soldiers capacity_icon",
		isPercent = 0,
		trueMul = nil,
		mul = nil,
		isTime = nil,
		isScientific = nil,
		count2Name = nil,
	},
	["addAtk"] = {
		cfgKey = "addAtk",
		index = 22,
		name = "attri_addAtk",
		icon = "ATK_icon",
		isPercent = 1,
		trueMul = nil,
		mul = nil,
		isTime = nil,
		isScientific = nil,
		count2Name = nil,
	},
	["addAtkSpeed"] = {
		cfgKey = "addAtkSpeed",
		index = 23,
		name = "attri_addAtkSpeed",
		icon = "Attack speed_icon",
		isPercent = 1,
		trueMul = nil,
		mul = nil,
		isTime = nil,
		isScientific = nil,
		count2Name = nil,
	},
	["addMoveSpeed"] = {
		cfgKey = "addMoveSpeed",
		index = 24,
		name = "attri_addMoveSpeed",
		icon = "Movement speed_icon",
		isPercent = 1,
		trueMul = nil,
		mul = nil,
		isTime = nil,
		isScientific = nil,
		count2Name = nil,
	},
	["cure"] = {
		cfgKey = "cure",
		index = 25,
		name = "attri_cure",
		icon = "Healing amount_icon",
		isPercent = 0,
		trueMul = nil,
		mul = nil,
		isTime = nil,
		isScientific = nil,
		count2Name = nil,
	},
	["lifeTime"] = {
		cfgKey = "lifeTime",
		index = 26,
		name = "attri_lifeTime",
		icon = "Training time_icon",
		isPercent = 0,
		trueMul = nil,
		mul = nil,
		isTime = nil,
		isScientific = nil,
		count2Name = nil,
	},
	["trainNeedStarCoin"] = {
		cfgKey = "trainNeedStarCoin",
		index = 27,
		name = "attri_trainNeedStarCoin",
		icon = "Training expenses_icon",
		isPercent = 0,
		trueMul = nil,
		mul = nil,
		isTime = nil,
		isScientific = nil,
		count2Name = nil,
	},
	["skillLevel"] = {
		cfgKey = "skillLevel",
		index = 28,
		name = "attri_skillLevel",
		icon = "Skill duration_icon",
		isPercent = 0,
		trueMul = nil,
		mul = nil,
		isTime = nil,
		isScientific = nil,
		count2Name = nil,
	},
	["skillPoint"] = {
		cfgKey = "skillPoint",
		index = 29,
		name = "attri_skillPoint",
		icon = "Energy_icon",
		isPercent = 0,
		trueMul = nil,
		mul = nil,
		isTime = nil,
		isScientific = nil,
		count2Name = nil,
	},
	["tonnage"] = {
		cfgKey = "tonnage",
		index = 30,
		name = "attri_tonnage",
		icon = "Acquisition capacity_cion",
		isPercent = 0,
		trueMul = nil,
		mul = nil,
		isTime = nil,
		isScientific = nil,
		count2Name = nil,
	},
	["flyTime"] = {
		cfgKey = "flyTime",
		index = 31,
		name = "attri_flyTime",
		icon = "Speed_icon",
		isPercent = 0,
		trueMul = nil,
		mul = nil,
		isTime = nil,
		isScientific = nil,
		count2Name = nil,
	},
	["trainSpace"] = {
		cfgKey = "trainSpace",
		index = 32,
		name = "attri_trainSpace",
		icon = "Space Required_icon",
		isPercent = 0,
		trueMul = nil,
		mul = nil,
		isTime = nil,
		isScientific = nil,
		count2Name = nil,
	},
	["trainNeedTick"] = {
		cfgKey = "trainNeedTick",
		index = 33,
		name = "attri_trainNeedTick",
		icon = "Training time_icon",
		isPercent = 0,
		trueMul = nil,
		mul = nil,
		isTime = 1,
		isScientific = nil,
		count2Name = nil,
	},
	["durability"] = {
		cfgKey = "durability",
		index = 34,
		name = "attri_durability",
		icon = "Durability_icon",
		isPercent = 0,
		trueMul = nil,
		mul = nil,
		isTime = nil,
		isScientific = nil,
		count2Name = nil,
	},
	["resProtectRatio"] = {
		cfgKey = "resProtectRatio",
		index = 35,
		name = "attri_protective",
		icon = "Protective number_icon",
		isPercent = 2,
		trueMul = nil,
		mul = nil,
		isTime = nil,
		isScientific = nil,
		count2Name = nil,
	},
	["power"] = {
		cfgKey = "power",
		index = 36,
		name = "attri_power",
		icon = "hashrate_icon",
		isPercent = 0,
		trueMul = nil,
		mul = nil,
		isTime = nil,
		isScientific = nil,
		count2Name = nil,
	},
	["race"] = {
		cfgKey = "race",
		index = 37,
		name = "attri_race",
		icon = "race_icon",
		isPercent = 0,
		trueMul = nil,
		mul = nil,
		isTime = nil,
		isScientific = nil,
		count2Name = nil,
	},
	["construction"] = {
		cfgKey = "construction",
		index = 38,
		name = "attri_buildPoints",
		icon = "build_icon",
		isPercent = 0,
		trueMul = nil,
		mul = nil,
		isTime = nil,
		isScientific = nil,
		count2Name = nil,
	},
	["Shrine_AtkAdd"] = {
		cfgKey = "Shrine_AtkAdd",
		index = 39,
		name = "attri_ShrineAddAtk",
		icon = "ATK_icon",
		isPercent = 0,
		trueMul = nil,
		mul = nil,
		isTime = nil,
		isScientific = nil,
		count2Name = nil,
	},
	["Shrine_HpAdd"] = {
		cfgKey = "Shrine_HpAdd",
		index = 40,
		name = "attri_ShrineAddHp",
		icon = "HP_icon",
		isPercent = 0,
		trueMul = nil,
		mul = nil,
		isTime = nil,
		isScientific = nil,
		count2Name = nil,
	},
	["translationRatio"] = {
		cfgKey = "translationRatio",
		index = 41,
		name = "attri_translationRatio",
		icon = "HP_icon",
		isPercent = 2,
		trueMul = nil,
		mul = nil,
		isTime = nil,
		isScientific = nil,
		count2Name = nil,
	},
	["quantumPotential"] = {
		cfgKey = "quantumPotential",
		index = 42,
		name = "attri_quantumPotential",
		icon = "Speed_icon",
		isPercent = 0,
		trueMul = nil,
		mul = nil,
		isTime = nil,
		isScientific = nil,
		count2Name = nil,
	},
	["atkAir"] = {
		cfgKey = "atkAir",
		index = 43,
		name = "attri_AtkType",
		icon = "Speed_icon",
		isPercent = 0,
		trueMul = nil,
		mul = nil,
		isTime = nil,
		isScientific = nil,
		count2Name = nil,
	},
}
