-- index                            int                              
-- cfgKey                           string                           key
-- isProperty                       int                              Property
-- name                             string                           
-- icon                             string                           
-- isPercent                        int                              

return {
	[1] = {
		index = 1,
		cfgKey = "maxHp",
		isProperty = 1,
		name = "Health",
		icon = "Icon_HeroHud_1",
		isPercent = 0,
	},
	[2] = {
		index = 2,
		cfgKey = "atk",
		isProperty = 1,
		name = "Damage per second",
		icon = "Icon_HeroHud_2",
		isPercent = 0,
	},
	[3] = {
		index = 3,
		cfgKey = "moveSpeed",
		isProperty = 1,
		name = "Moving speed",
		icon = "Icon_HeroHud_3",
		isPercent = 0,
	},
	[4] = {
		index = 4,
		cfgKey = "atkRange",
		isProperty = 1,
		name = "Range of attack",
		icon = "Icon_HeroHud_4",
		isPercent = 0,
	},
	[5] = {
		index = 5,
		cfgKey = "atkSpeed",
		isProperty = 1,
		name = "atkSpeed",
		icon = "Treatment_icon",
		isPercent = 0,
	},
	[6] = {
		index = 6,
		cfgKey = "perMakeStarCoin",
		isProperty = 0,
		name = "perMakeStarCoin",
		icon = "icon_starcoin_50",
		isPercent = 0,
	},
	[7] = {
		index = 7,
		cfgKey = "maxMakeStarCoin",
		isProperty = 0,
		name = "maxMakeStarCoin",
		icon = "icon_starcoin_50",
		isPercent = 0,
	},
	[8] = {
		index = 8,
		cfgKey = "perMakeIce",
		isProperty = 0,
		name = "perMakeIce",
		icon = "icon_ice_50",
		isPercent = 0,
	},
	[9] = {
		index = 9,
		cfgKey = "maxMakeIce",
		isProperty = 0,
		name = "maxMakeIce",
		icon = "icon_ice_50",
		isPercent = 0,
	},
	[10] = {
		index = 10,
		cfgKey = "perMakeCarboxyl",
		isProperty = 0,
		name = "perMakeCarboxyl",
		icon = "icon_hydroxyl_50",
		isPercent = 0,
	},
	[11] = {
		index = 11,
		cfgKey = "maxMakeCarboxyl",
		isProperty = 0,
		name = "maxMakeCarboxyl",
		icon = "icon_hydroxyl_50",
		isPercent = 0,
	},
	[12] = {
		index = 12,
		cfgKey = "perMakeTitanium",
		isProperty = 0,
		name = "perMakeTitanium",
		icon = "icon_titanium_50",
		isPercent = 0,
	},
	[13] = {
		index = 13,
		cfgKey = "maxMakeTitanium",
		isProperty = 0,
		name = "maxMakeTitanium",
		icon = "icon_titanium_50",
		isPercent = 0,
	},
	[14] = {
		index = 14,
		cfgKey = "perMakeGas",
		isProperty = 0,
		name = "perMakeGas",
		icon = "icon_gas_50",
		isPercent = 0,
	},
	[15] = {
		index = 15,
		cfgKey = "maxMakeGas",
		isProperty = 0,
		name = "maxMakeGas",
		icon = "icon_gas_50",
		isPercent = 0,
	},
	[16] = {
		index = 16,
		cfgKey = "storeStarCoin",
		isProperty = 0,
		name = "storeStarCoin",
		icon = "icon_starcoin_50",
		isPercent = 0,
	},
	[17] = {
		index = 17,
		cfgKey = "storeIce",
		isProperty = 0,
		name = "storeIce",
		icon = "icon_ice_50",
		isPercent = 0,
	},
	[18] = {
		index = 18,
		cfgKey = "storeCarboxyl",
		isProperty = 0,
		name = "storeCarboxyl",
		icon = "icon_hydroxyl_50",
		isPercent = 0,
	},
	[19] = {
		index = 19,
		cfgKey = "storeTitanium",
		isProperty = 0,
		name = "storeTitanium",
		icon = "icon_titanium_50",
		isPercent = 0,
	},
	[20] = {
		index = 20,
		cfgKey = "storeGas",
		isProperty = nil,
		name = "storeGas",
		icon = "icon_gas_50",
		isPercent = 0,
	},
	[21] = {
		index = 21,
		cfgKey = "maxTrainSpace",
		isProperty = nil,
		name = "maxTrainSpace",
		icon = "Treatment_icon",
		isPercent = 0,
	},
	[22] = {
		index = 22,
		cfgKey = "addAtk",
		isProperty = 1,
		name = "Attack power",
		icon = "Attack power_icon",
		isPercent = 1,
	},
	[23] = {
		index = 23,
		cfgKey = "addAtkSpeed",
		isProperty = nil,
		name = "Attack speed",
		icon = "Attack speed_icon",
		isPercent = 1,
	},
	[24] = {
		index = 24,
		cfgKey = "addMoveSpeed",
		isProperty = nil,
		name = "Moving speed",
		icon = "Moving speed_icon",
		isPercent = 1,
	},
	[25] = {
		index = 25,
		cfgKey = "cure",
		isProperty = 1,
		name = "Treatment",
		icon = "Treatment_icon",
		isPercent = 0,
	},
	[26] = {
		index = 26,
		cfgKey = "lifeTime",
		isProperty = nil,
		name = "Skill duration",
		icon = "Skill duration_icon",
		isPercent = 0,
	},
}
