-- cfgId                            int                              ""ID
-- beginAudio                       string                           ""
-- idleAudio                        string                           ""
-- moveAudio                        string                           ""
-- attackAudio                      string                           ""
-- dieAudio                         string                           ""
-- special1                         string                           ""
-- special2                         string                           ""2
-- special3                         string                           ""3
-- bank                             string                           Bank

return {
	[3000001] = {
		cfgId = 3000001,
		beginAudio = "",
		idleAudio = "",
		moveAudio = "",
		attackAudio = "",
		dieAudio = "event:/build_dead",
		special1 = "",
		special2 = "",
		special3 = "",
		bank = "",
	},
	[3000002] = {
		cfgId = 3000002,
		beginAudio = "",
		idleAudio = "",
		moveAudio = "",
		attackAudio = "",
		dieAudio = "event:/build_dead",
		special1 = "",
		special2 = "",
		special3 = "",
		bank = "",
	},
	[3000003] = {
		cfgId = 3000003,
		beginAudio = "",
		idleAudio = "",
		moveAudio = "",
		attackAudio = "",
		dieAudio = "event:/build_dead",
		special1 = "",
		special2 = "",
		special3 = "",
		bank = "",
	},
	[3000004] = {
		cfgId = 3000004,
		beginAudio = "",
		idleAudio = "",
		moveAudio = "",
		attackAudio = "",
		dieAudio = "event:/build_dead",
		special1 = "",
		special2 = "",
		special3 = "",
		bank = "",
	},
	[3000005] = {
		cfgId = 3000005,
		beginAudio = "",
		idleAudio = "",
		moveAudio = "",
		attackAudio = "",
		dieAudio = "event:/build_dead",
		special1 = "",
		special2 = "",
		special3 = "",
		bank = "",
	},
	[3000006] = {
		cfgId = 3000006,
		beginAudio = "",
		idleAudio = "",
		moveAudio = "",
		attackAudio = "",
		dieAudio = "event:/build_dead",
		special1 = "",
		special2 = "",
		special3 = "",
		bank = "",
	},
	[3000007] = {
		cfgId = 3000007,
		beginAudio = "",
		idleAudio = "",
		moveAudio = "",
		attackAudio = "",
		dieAudio = "event:/build_dead",
		special1 = "",
		special2 = "",
		special3 = "",
		bank = "",
	},
	[3000008] = {
		cfgId = 3000008,
		beginAudio = "",
		idleAudio = "",
		moveAudio = "",
		attackAudio = "",
		dieAudio = "event:/build_dead",
		special1 = "",
		special2 = "",
		special3 = "",
		bank = "",
	},
	[3000009] = {
		cfgId = 3000009,
		beginAudio = "",
		idleAudio = "",
		moveAudio = "",
		attackAudio = "",
		dieAudio = "event:/build_dead",
		special1 = "",
		special2 = "",
		special3 = "",
		bank = "",
	},
	[3000010] = {
		cfgId = 3000010,
		beginAudio = "",
		idleAudio = "",
		moveAudio = "",
		attackAudio = "",
		dieAudio = "event:/build_dead",
		special1 = "",
		special2 = "",
		special3 = "",
		bank = "",
	},
	[3000011] = {
		cfgId = 3000011,
		beginAudio = "",
		idleAudio = "",
		moveAudio = "",
		attackAudio = "",
		dieAudio = "event:/build_dead",
		special1 = "",
		special2 = "",
		special3 = "",
		bank = "",
	},
	[3000012] = {
		cfgId = 3000012,
		beginAudio = "",
		idleAudio = "",
		moveAudio = "",
		attackAudio = "",
		dieAudio = "event:/build_dead",
		special1 = "",
		special2 = "",
		special3 = "",
		bank = "",
	},
	[3000013] = {
		cfgId = 3000013,
		beginAudio = "",
		idleAudio = "",
		moveAudio = "",
		attackAudio = "",
		dieAudio = "event:/build_dead",
		special1 = "",
		special2 = "",
		special3 = "",
		bank = "",
	},
	[3000014] = {
		cfgId = 3000014,
		beginAudio = "",
		idleAudio = "",
		moveAudio = "",
		attackAudio = "",
		dieAudio = "event:/build_dead",
		special1 = "",
		special2 = "",
		special3 = "",
		bank = "",
	},
	[3000015] = {
		cfgId = 3000015,
		beginAudio = "",
		idleAudio = "",
		moveAudio = "",
		attackAudio = "",
		dieAudio = "event:/build_dead",
		special1 = "",
		special2 = "",
		special3 = "",
		bank = "",
	},
	[3000100] = {
		cfgId = 3000100,
		beginAudio = "",
		idleAudio = "",
		moveAudio = "",
		attackAudio = "",
		dieAudio = "event:/build_dead",
		special1 = "",
		special2 = "",
		special3 = "",
		bank = "se_Build_LaserGun",
	},
	[3000101] = {
		cfgId = 3000101,
		beginAudio = "",
		idleAudio = "",
		moveAudio = "",
		attackAudio = "",
		dieAudio = "event:/build_dead",
		special1 = "",
		special2 = "",
		special3 = "",
		bank = "se_Build_ParticlebeamTower",
	},
	[3000102] = {
		cfgId = 3000102,
		beginAudio = "",
		idleAudio = "",
		moveAudio = "",
		attackAudio = "",
		dieAudio = "event:/build_dead",
		special1 = "",
		special2 = "",
		special3 = "",
		bank = "se_Build_DestructionParticleArtillery",
	},
	[3000103] = {
		cfgId = 3000103,
		beginAudio = "",
		idleAudio = "",
		moveAudio = "",
		attackAudio = "",
		dieAudio = "event:/build_dead",
		special1 = "",
		special2 = "",
		special3 = "",
		bank = "se_Build_HypersonicMissile",
	},
	[3000104] = {
		cfgId = 3000104,
		beginAudio = "",
		idleAudio = "",
		moveAudio = "",
		attackAudio = "",
		dieAudio = "event:/build_dead",
		special1 = "",
		special2 = "",
		special3 = "",
		bank = "",
	},
	[3000105] = {
		cfgId = 3000105,
		beginAudio = "",
		idleAudio = "",
		moveAudio = "",
		attackAudio = "",
		dieAudio = "event:/build_dead",
		special1 = "",
		special2 = "",
		special3 = "",
		bank = "se_Build_AntiaircraftMissile",
	},
	[3000106] = {
		cfgId = 3000106,
		beginAudio = "",
		idleAudio = "",
		moveAudio = "",
		attackAudio = "",
		dieAudio = "event:/build_dead",
		special1 = "",
		special2 = "",
		special3 = "",
		bank = "se_Build_MicroBlackHole",
	},
	[3000107] = {
		cfgId = 3000107,
		beginAudio = "",
		idleAudio = "",
		moveAudio = "",
		attackAudio = "",
		dieAudio = "",
		special1 = "",
		special2 = "",
		special3 = "",
		bank = "",
	},
	[5105001] = {
		cfgId = 5105001,
		beginAudio = "",
		idleAudio = "",
		moveAudio = "",
		attackAudio = "",
		dieAudio = "",
		special1 = "",
		special2 = "",
		special3 = "",
		bank = "",
	},
	[5106001] = {
		cfgId = 5106001,
		beginAudio = "",
		idleAudio = "",
		moveAudio = "",
		attackAudio = "",
		dieAudio = "",
		special1 = "",
		special2 = "",
		special3 = "",
		bank = "",
	},
	[5107001] = {
		cfgId = 5107001,
		beginAudio = "",
		idleAudio = "",
		moveAudio = "",
		attackAudio = "",
		dieAudio = "",
		special1 = "",
		special2 = "",
		special3 = "",
		bank = "",
	},
	[5109001] = {
		cfgId = 5109001,
		beginAudio = "",
		idleAudio = "",
		moveAudio = "",
		attackAudio = "",
		dieAudio = "",
		special1 = "",
		special2 = "",
		special3 = "",
		bank = "",
	},
	[5111001] = {
		cfgId = 5111001,
		beginAudio = "",
		idleAudio = "",
		moveAudio = "",
		attackAudio = "",
		dieAudio = "",
		special1 = "",
		special2 = "",
		special3 = "",
		bank = "",
	},
	[5116022] = {
		cfgId = 5116022,
		beginAudio = "",
		idleAudio = "",
		moveAudio = "",
		attackAudio = "",
		dieAudio = "",
		special1 = "",
		special2 = "",
		special3 = "",
		bank = "",
	},
	[5116023] = {
		cfgId = 5116023,
		beginAudio = "",
		idleAudio = "",
		moveAudio = "",
		attackAudio = "",
		dieAudio = "",
		special1 = "",
		special2 = "",
		special3 = "",
		bank = "",
	},
	[5116024] = {
		cfgId = 5116024,
		beginAudio = "",
		idleAudio = "",
		moveAudio = "",
		attackAudio = "",
		dieAudio = "",
		special1 = "",
		special2 = "",
		special3 = "",
		bank = "",
	},
	[5116025] = {
		cfgId = 5116025,
		beginAudio = "",
		idleAudio = "",
		moveAudio = "",
		attackAudio = "",
		dieAudio = "",
		special1 = "",
		special2 = "",
		special3 = "",
		bank = "",
	},
	[5116026] = {
		cfgId = 5116026,
		beginAudio = "",
		idleAudio = "",
		moveAudio = "",
		attackAudio = "",
		dieAudio = "",
		special1 = "",
		special2 = "",
		special3 = "",
		bank = "",
	},
	[6100011] = {
		cfgId = 6100011,
		beginAudio = "event:/Skill_240000101",
		idleAudio = "",
		moveAudio = "",
		attackAudio = "",
		dieAudio = "",
		special1 = "",
		special2 = "",
		special3 = "",
		bank = "",
	},
	[6100012] = {
		cfgId = 6100012,
		beginAudio = "event:/Skill_240000201",
		idleAudio = "",
		moveAudio = "",
		attackAudio = "",
		dieAudio = "",
		special1 = "",
		special2 = "",
		special3 = "",
		bank = "",
	},
	[6100013] = {
		cfgId = 6100013,
		beginAudio = "event:/Skill_500000101",
		idleAudio = "",
		moveAudio = "",
		attackAudio = "",
		dieAudio = "",
		special1 = "",
		special2 = "",
		special3 = "",
		bank = "",
	},
	[6100023] = {
		cfgId = 6100023,
		beginAudio = "event:/Skill_230000101",
		idleAudio = "",
		moveAudio = "",
		attackAudio = "",
		dieAudio = "",
		special1 = "",
		special2 = "",
		special3 = "",
		bank = "",
	},
	[6100025] = {
		cfgId = 6100025,
		beginAudio = "event:/Skill_230000201",
		idleAudio = "",
		moveAudio = "",
		attackAudio = "",
		dieAudio = "",
		special1 = "",
		special2 = "",
		special3 = "",
		bank = "",
	},
	[6100027] = {
		cfgId = 6100027,
		beginAudio = "event:/Skill_230000101",
		idleAudio = "",
		moveAudio = "",
		attackAudio = "",
		dieAudio = "",
		special1 = "",
		special2 = "",
		special3 = "",
		bank = "",
	},
	[6100028] = {
		cfgId = 6100028,
		beginAudio = "event:/Skill_230000201",
		idleAudio = "",
		moveAudio = "",
		attackAudio = "",
		dieAudio = "",
		special1 = "",
		special2 = "",
		special3 = "",
		bank = "",
	},
	[6100029] = {
		cfgId = 6100029,
		beginAudio = "event:/Skill_210000101",
		idleAudio = "",
		moveAudio = "",
		attackAudio = "",
		dieAudio = "",
		special1 = "",
		special2 = "",
		special3 = "",
		bank = "",
	},
	[6100030] = {
		cfgId = 6100030,
		beginAudio = "event:/Skill_210000201",
		idleAudio = "",
		moveAudio = "",
		attackAudio = "",
		dieAudio = "",
		special1 = "",
		special2 = "",
		special3 = "",
		bank = "",
	},
	[6100033] = {
		cfgId = 6100033,
		beginAudio = "event:/Skill_510000101",
		idleAudio = "",
		moveAudio = "",
		attackAudio = "",
		dieAudio = "",
		special1 = "",
		special2 = "",
		special3 = "",
		bank = "",
	},
	[6100034] = {
		cfgId = 6100034,
		beginAudio = "event:/Skill_520000101",
		idleAudio = "",
		moveAudio = "",
		attackAudio = "",
		dieAudio = "",
		special1 = "",
		special2 = "",
		special3 = "",
		bank = "",
	},
	[6100035] = {
		cfgId = 6100035,
		beginAudio = "event:/Skill_530000101",
		idleAudio = "",
		moveAudio = "",
		attackAudio = "",
		dieAudio = "",
		special1 = "",
		special2 = "",
		special3 = "",
		bank = "",
	},
	[6100036] = {
		cfgId = 6100036,
		beginAudio = "event:/Skill_540000101",
		idleAudio = "",
		moveAudio = "",
		attackAudio = "",
		dieAudio = "",
		special1 = "",
		special2 = "",
		special3 = "",
		bank = "",
	},
	[6100037] = {
		cfgId = 6100037,
		beginAudio = "event:/Skill_510000201",
		idleAudio = "",
		moveAudio = "",
		attackAudio = "",
		dieAudio = "",
		special1 = "",
		special2 = "",
		special3 = "",
		bank = "",
	},
	[6100038] = {
		cfgId = 6100038,
		beginAudio = "event:/Skill_520000201",
		idleAudio = "",
		moveAudio = "",
		attackAudio = "",
		dieAudio = "",
		special1 = "",
		special2 = "",
		special3 = "",
		bank = "",
	},
	[6100039] = {
		cfgId = 6100039,
		beginAudio = "event:/Skill_530000201",
		idleAudio = "",
		moveAudio = "",
		attackAudio = "",
		dieAudio = "",
		special1 = "",
		special2 = "",
		special3 = "",
		bank = "",
	},
	[6100040] = {
		cfgId = 6100040,
		beginAudio = "event:/Skill_540000201",
		idleAudio = "",
		moveAudio = "",
		attackAudio = "",
		dieAudio = "",
		special1 = "",
		special2 = "",
		special3 = "",
		bank = "",
	},
}
