-- cfgId                            int                              ""ID
-- name                             string                           ""
-- desc                             string                           ""
-- model                            string                           ""
-- explosionEffect                  string                           ""
-- buffCfgId                        int                              ""buff""id
-- type                             int                              ""(1："" 2："" 3：AOE"" 4：AOE"" 5："" 6:"" 7："" 8："" 9：""    10："" 11："")
-- moveSpeed                        int                              ""("" ""；""type ""5，"")
-- atkRange                         int                              ""("") (""AOE""0。""9："")
-- atkWidth                         int                              ""("")
-- bulletCfgId                      int                              ""id（""，""0）
-- vanishTime                       int                              ""("")

return {
	[8201001] = {
		cfgId = 8201001,
		name = "",
		desc = "",
		model = "Bullet_Particlegunner",
		explosionEffect = "",
		buffCfgId = nil,
		type = 1,
		moveSpeed = 20000,
		atkRange = nil,
		atkWidth = nil,
		bulletCfgId = nil,
		vanishTime = 0,
	},
	[8202001] = {
		cfgId = 8202001,
		name = "",
		desc = "",
		model = "Bullet_Particlegunner",
		explosionEffect = "",
		buffCfgId = nil,
		type = 1,
		moveSpeed = 20000,
		atkRange = nil,
		atkWidth = nil,
		bulletCfgId = nil,
		vanishTime = 0,
	},
	[8203001] = {
		cfgId = 8203001,
		name = "",
		desc = "",
		model = "",
		explosionEffect = "",
		buffCfgId = nil,
		type = 1,
		moveSpeed = 20000,
		atkRange = nil,
		atkWidth = nil,
		bulletCfgId = nil,
		vanishTime = 0,
	},
	[8204001] = {
		cfgId = 8204001,
		name = "",
		desc = "",
		model = "Bullet_Dot",
		explosionEffect = "Eff_BuildingDie_1x1",
		buffCfgId = nil,
		type = 1,
		moveSpeed = 30000,
		atkRange = nil,
		atkWidth = nil,
		bulletCfgId = nil,
		vanishTime = 0,
	},
	[8205001] = {
		cfgId = 8205001,
		name = "",
		desc = "",
		model = "Bullet_flame",
		explosionEffect = "",
		buffCfgId = 7105001,
		type = 1,
		moveSpeed = 10000,
		atkRange = nil,
		atkWidth = nil,
		bulletCfgId = nil,
		vanishTime = 500,
	},
	[8206001] = {
		cfgId = 8206001,
		name = "",
		desc = "",
		model = "",
		explosionEffect = "",
		buffCfgId = nil,
		type = 1,
		moveSpeed = 20000,
		atkRange = nil,
		atkWidth = nil,
		bulletCfgId = nil,
		vanishTime = 0,
	},
	[8207001] = {
		cfgId = 8207001,
		name = "",
		desc = "",
		model = "Bullet_Particlegunner",
		explosionEffect = "",
		buffCfgId = nil,
		type = 1,
		moveSpeed = 20000,
		atkRange = nil,
		atkWidth = nil,
		bulletCfgId = nil,
		vanishTime = 0,
	},
	[8208001] = {
		cfgId = 8208001,
		name = "",
		desc = "",
		model = "Bullet_Sirius",
		explosionEffect = "",
		buffCfgId = nil,
		type = 1,
		moveSpeed = 20000,
		atkRange = nil,
		atkWidth = nil,
		bulletCfgId = nil,
		vanishTime = 0,
	},
	[8209001] = {
		cfgId = 8209001,
		name = "",
		desc = "",
		model = "",
		explosionEffect = "",
		buffCfgId = nil,
		type = 1,
		moveSpeed = 20000,
		atkRange = nil,
		atkWidth = nil,
		bulletCfgId = nil,
		vanishTime = 0,
	},
	[8210001] = {
		cfgId = 8210001,
		name = "",
		desc = "",
		model = "Bullet_Sonicemitter",
		explosionEffect = "",
		buffCfgId = nil,
		type = 9,
		moveSpeed = 30000,
		atkRange = 15000,
		atkWidth = 1000,
		bulletCfgId = nil,
		vanishTime = 0,
	},
	[8211001] = {
		cfgId = 8211001,
		name = "",
		desc = "",
		model = "Bullet_Ather",
		explosionEffect = "Eff_AtherDie",
		buffCfgId = nil,
		type = 6,
		moveSpeed = 3000,
		atkRange = 6000,
		atkWidth = nil,
		bulletCfgId = 8212001,
		vanishTime = 0,
	},
	[8212001] = {
		cfgId = 8212001,
		name = "",
		desc = "",
		model = "Bullet_AtherDivision",
		explosionEffect = "Eff_AtherDivisionDie",
		buffCfgId = nil,
		type = 7,
		moveSpeed = 20000,
		atkRange = 500,
		atkWidth = nil,
		bulletCfgId = nil,
		vanishTime = 0,
	},
	[8213001] = {
		cfgId = 8213001,
		name = "",
		desc = "",
		model = "Bullet_Particlegunner",
		explosionEffect = "",
		buffCfgId = nil,
		type = 1,
		moveSpeed = 20000,
		atkRange = nil,
		atkWidth = nil,
		bulletCfgId = nil,
		vanishTime = 0,
	},
	[8214001] = {
		cfgId = 8214001,
		name = "",
		desc = "",
		model = "Bullet_Missile",
		explosionEffect = "Eff_AtherDivisionDie",
		buffCfgId = nil,
		type = 3,
		moveSpeed = 20000,
		atkRange = 500,
		atkWidth = nil,
		bulletCfgId = nil,
		vanishTime = 0,
	},
	[8301001] = {
		cfgId = 8301001,
		name = "",
		desc = "",
		model = "Bullet_Missile",
		explosionEffect = "",
		buffCfgId = nil,
		type = 1,
		moveSpeed = 25000,
		atkRange = nil,
		atkWidth = nil,
		bulletCfgId = nil,
		vanishTime = 0,
	},
	[8302001] = {
		cfgId = 8302001,
		name = "",
		desc = "",
		model = "Bullet_Dot",
		explosionEffect = "",
		buffCfgId = 7106001,
		type = 1,
		moveSpeed = 30000,
		atkRange = nil,
		atkWidth = nil,
		bulletCfgId = nil,
		vanishTime = 0,
	},
	[8303001] = {
		cfgId = 8303001,
		name = "",
		desc = "",
		model = "Bullet_Thelasergun",
		explosionEffect = "Eff_BuildingDie_1x1",
		buffCfgId = nil,
		type = 3,
		moveSpeed = 20000,
		atkRange = 500,
		atkWidth = nil,
		bulletCfgId = nil,
		vanishTime = 0,
	},
	[8304001] = {
		cfgId = 8304001,
		name = "",
		desc = "",
		model = "Bullet_Sonicemitter",
		explosionEffect = "",
		buffCfgId = nil,
		type = 9,
		moveSpeed = 40000,
		atkRange = 18000,
		atkWidth = 2500,
		bulletCfgId = nil,
		vanishTime = 200,
	},
	[8305001] = {
		cfgId = 8305001,
		name = "",
		desc = "",
		model = "",
		explosionEffect = "Bullet_EMP",
		buffCfgId = 7207001,
		type = 8,
		moveSpeed = 20000,
		atkRange = 5000,
		atkWidth = nil,
		bulletCfgId = nil,
		vanishTime = 0,
	},
	[8306001] = {
		cfgId = 8306001,
		name = "",
		desc = "",
		model = "Bullet_MetalMissile",
		explosionEffect = "Eff_BuildingDie_1x1",
		buffCfgId = nil,
		type = 1,
		moveSpeed = 35000,
		atkRange = nil,
		atkWidth = nil,
		bulletCfgId = nil,
		vanishTime = 0,
	},
	[8307001] = {
		cfgId = 8307001,
		name = "",
		desc = "",
		model = "Bullet_Lightning",
		explosionEffect = "",
		buffCfgId = nil,
		type = 5,
		moveSpeed = 20000,
		atkRange = nil,
		atkWidth = nil,
		bulletCfgId = nil,
		vanishTime = 0,
	},
	[8308001] = {
		cfgId = 8308001,
		name = "",
		desc = "",
		model = "Bullet_Laser",
		explosionEffect = "",
		buffCfgId = nil,
		type = 1,
		moveSpeed = 20000,
		atkRange = nil,
		atkWidth = nil,
		bulletCfgId = nil,
		vanishTime = 0,
	},
	[8101001] = {
		cfgId = 8101001,
		name = "",
		desc = "",
		model = "Bullet_Particlegunner",
		explosionEffect = "",
		buffCfgId = nil,
		type = 1,
		moveSpeed = 20000,
		atkRange = nil,
		atkWidth = nil,
		bulletCfgId = nil,
		vanishTime = 0,
	},
	[8102001] = {
		cfgId = 8102001,
		name = "",
		desc = "",
		model = "Bullet_Particlegunner",
		explosionEffect = "",
		buffCfgId = nil,
		type = 1,
		moveSpeed = 20000,
		atkRange = nil,
		atkWidth = nil,
		bulletCfgId = nil,
		vanishTime = 0,
	},
	[8103001] = {
		cfgId = 8103001,
		name = "",
		desc = "",
		model = "Bullet_Talus",
		explosionEffect = "",
		buffCfgId = nil,
		type = 1,
		moveSpeed = 20000,
		atkRange = nil,
		atkWidth = nil,
		bulletCfgId = nil,
		vanishTime = 0,
	},
	[8104001] = {
		cfgId = 8104001,
		name = "",
		desc = "",
		model = "Bullet_Particlegunner",
		explosionEffect = "",
		buffCfgId = nil,
		type = 1,
		moveSpeed = 20000,
		atkRange = nil,
		atkWidth = nil,
		bulletCfgId = nil,
		vanishTime = 0,
	},
	[8105001] = {
		cfgId = 8105001,
		name = "",
		desc = "",
		model = "Bullet_Particlegunner",
		explosionEffect = "",
		buffCfgId = nil,
		type = 1,
		moveSpeed = 20000,
		atkRange = nil,
		atkWidth = nil,
		bulletCfgId = nil,
		vanishTime = 0,
	},
	[8105002] = {
		cfgId = 8105002,
		name = "",
		desc = "",
		model = "Bullet_Missile",
		explosionEffect = "",
		buffCfgId = nil,
		type = 11,
		moveSpeed = 40000,
		atkRange = 2000,
		atkWidth = nil,
		bulletCfgId = nil,
		vanishTime = nil,
	},
}
