-- cfgId                            int                              ""ID
-- languageNameID                   string                           ""ID
-- icon                             string                           ""
-- isShow                           int                              ""(1-""，2-""）

return {
	[1] = {
		cfgId = 1,
		languageNameID = "flag_logo",
		icon = "logo_Flag_icon",
		isShow = 1,
	},
	[2] = {
		cfgId = 2,
		languageNameID = "flag_B",
		icon = "the national flag_icon_B",
		isShow = 2,
	},
	[3] = {
		cfgId = 3,
		languageNameID = "flag_C",
		icon = "the national flag_icon_C",
		isShow = 2,
	},
	[4] = {
		cfgId = 4,
		languageNameID = "Finland_Flag_icon",
		icon = "Finland_Flag_icon",
		isShow = 2,
	},
	[5] = {
		cfgId = 5,
		languageNameID = "flag_Algeria",
		icon = "Algeria_Flag_icon",
		isShow = 1,
	},
	[6] = {
		cfgId = 6,
		languageNameID = "flag_America",
		icon = "America_Flag_icon",
		isShow = 1,
	},
	[7] = {
		cfgId = 7,
		languageNameID = "flag_Argentina",
		icon = "Argentina_Flag_icon",
		isShow = 1,
	},
	[8] = {
		cfgId = 8,
		languageNameID = "flag_Australia",
		icon = "Australia_Flag_icon",
		isShow = 1,
	},
	[9] = {
		cfgId = 9,
		languageNameID = "flag_Belgium",
		icon = "Belgium_Flag_icon",
		isShow = 1,
	},
	[10] = {
		cfgId = 10,
		languageNameID = "flag_Brazil",
		icon = "Brazil_Flag_icon",
		isShow = 1,
	},
	[11] = {
		cfgId = 11,
		languageNameID = "flag_Britain",
		icon = "Britain_Flag_icon",
		isShow = 1,
	},
	[12] = {
		cfgId = 12,
		languageNameID = "flag_Canada",
		icon = "Canada_Flag_icon",
		isShow = 1,
	},
	[13] = {
		cfgId = 13,
		languageNameID = "flag_China",
		icon = "China_Flag_icon",
		isShow = 2,
	},
	[14] = {
		cfgId = 14,
		languageNameID = "flag_Columbia",
		icon = "Columbia_Flag_icon",
		isShow = 1,
	},
	[15] = {
		cfgId = 15,
		languageNameID = "flag_DominicanRepublic",
		icon = "DominicanRepublic_Flag_icon",
		isShow = 1,
	},
	[16] = {
		cfgId = 16,
		languageNameID = "flag_Finland",
		icon = "Finland_Flag_icon",
		isShow = 1,
	},
	[17] = {
		cfgId = 17,
		languageNameID = "flag_French",
		icon = "French_Flag_icon",
		isShow = 1,
	},
	[18] = {
		cfgId = 18,
		languageNameID = "flag_Germany",
		icon = "Germany_Flag_icon",
		isShow = 1,
	},
	[19] = {
		cfgId = 19,
		languageNameID = "flag_India",
		icon = "India_Flag_icon",
		isShow = 1,
	},
	[20] = {
		cfgId = 20,
		languageNameID = "flag_Indonesia",
		icon = "Indonesia_Flag_icon",
		isShow = 1,
	},
	[21] = {
		cfgId = 21,
		languageNameID = "flag_Iran",
		icon = "Iran_Flag_icon",
		isShow = 1,
	},
	[22] = {
		cfgId = 22,
		languageNameID = "flag_Italy",
		icon = "Italy_Flag_icon",
		isShow = 1,
	},
	[23] = {
		cfgId = 23,
		languageNameID = "flag_Japan",
		icon = "Japan_Flag_icon",
		isShow = 1,
	},
	[24] = {
		cfgId = 24,
		languageNameID = "flag_LithuaniaRepublic",
		icon = "LithuaniaRepublic_Flag_icon",
		isShow = 1,
	},
	[25] = {
		cfgId = 25,
		languageNameID = "flag_Malaysia",
		icon = "Malaysia_Flag_icon",
		isShow = 1,
	},
	[26] = {
		cfgId = 26,
		languageNameID = "flag_Mexico",
		icon = "Mexico_Flag_icon",
		isShow = 1,
	},
	[27] = {
		cfgId = 27,
		languageNameID = "flag_Morocco",
		icon = "Morocco_Flag_icon",
		isShow = 1,
	},
	[28] = {
		cfgId = 28,
		languageNameID = "flag_Netherland",
		icon = "Netherland_Flag_icon",
		isShow = 1,
	},
	[29] = {
		cfgId = 29,
		languageNameID = "flag_Philippines",
		icon = "Philippines_Flag_icon",
		isShow = 1,
	},
	[30] = {
		cfgId = 30,
		languageNameID = "flag_PolandRepublic",
		icon = "PolandRepublic_Flag_icon",
		isShow = 1,
	},
	[31] = {
		cfgId = 31,
		languageNameID = "flag_Portugal",
		icon = "Portugal_Flag_icon",
		isShow = 1,
	},
	[32] = {
		cfgId = 32,
		languageNameID = "flag_Romania",
		icon = "Romania_Flag_icon",
		isShow = 1,
	},
	[33] = {
		cfgId = 33,
		languageNameID = "flag_Russia",
		icon = "Russia_Flag_icon",
		isShow = 1,
	},
	[34] = {
		cfgId = 34,
		languageNameID = "flag_SaudiArabia",
		icon = "SaudiArabia_Flag_icon",
		isShow = 1,
	},
	[35] = {
		cfgId = 35,
		languageNameID = "flag_SierraLeone",
		icon = "SierraLeone_Flag_icon",
		isShow = 1,
	},
	[36] = {
		cfgId = 36,
		languageNameID = "flag_Singapore",
		icon = "Singapore_Flag_icon",
		isShow = 1,
	},
	[37] = {
		cfgId = 37,
		languageNameID = "flag_SouthKorea",
		icon = "SouthKorea_Flag_icon",
		isShow = 1,
	},
	[38] = {
		cfgId = 38,
		languageNameID = "flag_Spain",
		icon = "Spain_Flag_icon",
		isShow = 1,
	},
	[39] = {
		cfgId = 39,
		languageNameID = "flag_Thailand",
		icon = "Thailand_Flag_icon",
		isShow = 1,
	},
	[40] = {
		cfgId = 40,
		languageNameID = "flag_Turkey",
		icon = "Turkey_Flag_icon",
		isShow = 1,
	},
	[41] = {
		cfgId = 41,
		languageNameID = "flag_Ukraine",
		icon = "Ukraine_Flag_icon",
		isShow = 1,
	},
	[42] = {
		cfgId = 42,
		languageNameID = "flag_Vietnam",
		icon = "Vietnam_Flag_icon",
		isShow = 1,
	},
	[43] = {
		cfgId = 43,
		languageNameID = "flag_Bangladesh",
		icon = "Bangladesh_Flag_icon",
		isShow = 1,
	},
	[44] = {
		cfgId = 44,
		languageNameID = "flag_Benin",
		icon = "Benin_Flag_icon",
		isShow = 1,
	},
	[45] = {
		cfgId = 45,
		languageNameID = "flag_Bolivia",
		icon = "Bolivia_Flag_icon",
		isShow = 1,
	},
	[46] = {
		cfgId = 46,
		languageNameID = "flag_BosniaAndHerzegovina",
		icon = "Bosé_Flag_icon",
		isShow = 2,
	},
	[47] = {
		cfgId = 47,
		languageNameID = "flag_Botswana",
		icon = "Botswana_Flag_icon",
		isShow = 1,
	},
	[48] = {
		cfgId = 48,
		languageNameID = "flag_Bulgaria",
		icon = "Bulgaria_Flag_icon",
		isShow = 1,
	},
	[49] = {
		cfgId = 49,
		languageNameID = "flag_Cameroon",
		icon = "Cameroon_Flag_icon",
		isShow = 1,
	},
	[50] = {
		cfgId = 50,
		languageNameID = "flag_CentralAfricanRepublic",
		icon = "CentralAfricanRepublic_Flag_icon",
		isShow = 1,
	},
	[51] = {
		cfgId = 51,
		languageNameID = "flag_Chile",
		icon = "Chile_Flag_icon",
		isShow = 1,
	},
	[52] = {
		cfgId = 52,
		languageNameID = "flag_Combodia",
		icon = "Combodia_Flag_icon",
		isShow = 1,
	},
	[53] = {
		cfgId = 53,
		languageNameID = "flag_CommonwealthOfTheBahamas",
		icon = "CommonwealthOfTheBahamas_Flag_icon",
		isShow = 1,
	},
	[54] = {
		cfgId = 54,
		languageNameID = "flag_Croatia",
		icon = "Croatia_Flag_icon",
		isShow = 1,
	},
	[55] = {
		cfgId = 55,
		languageNameID = "flag_Cuba",
		icon = "Cuba_Flag_icon",
		isShow = 1,
	},
	[56] = {
		cfgId = 56,
		languageNameID = "flag_CzechRepublic",
		icon = "CzechRepublic_Flag_icon",
		isShow = 1,
	},
	[57] = {
		cfgId = 57,
		languageNameID = "flag_CoteDIvoire",
		icon = "CôteD'Ivoire_Flag_icon",
		isShow = 1,
	},
	[58] = {
		cfgId = 58,
		languageNameID = "flag_Denmark",
		icon = "Denmark_Flag_icon",
		isShow = 1,
	},
	[59] = {
		cfgId = 59,
		languageNameID = "flag_Djibouti",
		icon = "Djibouti_Flag_icon",
		isShow = 1,
	},
	[60] = {
		cfgId = 60,
		languageNameID = "flag_Ecuador",
		icon = "Ecuador_Flag_icon",
		isShow = 1,
	},
	[61] = {
		cfgId = 61,
		languageNameID = "flag_Ethiopia",
		icon = "Ethiopia_Flag_icon",
		isShow = 1,
	},
	[62] = {
		cfgId = 62,
		languageNameID = "flag_Ghana",
		icon = "Ghana_Flag_icon",
		isShow = 1,
	},
	[63] = {
		cfgId = 63,
		languageNameID = "flag_Greece",
		icon = "Greece_Flag_icon",
		isShow = 1,
	},
	[64] = {
		cfgId = 64,
		languageNameID = "flag_Guinea",
		icon = "Guinea_Flag_icon",
		isShow = 1,
	},
	[65] = {
		cfgId = 65,
		languageNameID = "flag_Honduras",
		icon = "Honduras_Flag_icon",
		isShow = 1,
	},
	[66] = {
		cfgId = 66,
		languageNameID = "flag_Hungary",
		icon = "Hungary_Flag_icon",
		isShow = 1,
	},
	[67] = {
		cfgId = 67,
		languageNameID = "flag_Iceland",
		icon = "Iceland_Flag_icon",
		isShow = 1,
	},
	[68] = {
		cfgId = 68,
		languageNameID = "flag_Iraq",
		icon = "Iraq_Flag_icon",
		isShow = 1,
	},
	[69] = {
		cfgId = 69,
		languageNameID = "flag_Ireland",
		icon = "Ireland_Flag_icon",
		isShow = 1,
	},
	[70] = {
		cfgId = 70,
		languageNameID = "flag_Israel",
		icon = "Israel_Flag_icon",
		isShow = 1,
	},
	[71] = {
		cfgId = 71,
		languageNameID = "flag_Jamaica",
		icon = "Jamaica_Flag_icon",
		isShow = 1,
	},
	[72] = {
		cfgId = 72,
		languageNameID = "flag_Kazakhstan",
		icon = "Kazakhstan_Flag_icon",
		isShow = 1,
	},
	[73] = {
		cfgId = 73,
		languageNameID = "flag_Kenya",
		icon = "Kenya_Flag_icon",
		isShow = 1,
	},
	[74] = {
		cfgId = 74,
		languageNameID = "flag_Kuwait",
		icon = "Kuwait_Flag_icon",
		isShow = 1,
	},
	[75] = {
		cfgId = 75,
		languageNameID = "flag_Kyrgyzstan",
		icon = "Kyrgyzstan_Flag_icon",
		isShow = 1,
	},
	[76] = {
		cfgId = 76,
		languageNameID = "flag_Latvia",
		icon = "Latvia_Flag_icon",
		isShow = 1,
	},
	[77] = {
		cfgId = 77,
		languageNameID = "flag_Liechtenstein",
		icon = "Liechtenstein_Flag_icon",
		isShow = 1,
	},
	[78] = {
		cfgId = 78,
		languageNameID = "flag_Madagascar",
		icon = "Madagascar_Flag_icon",
		isShow = 1,
	},
	[79] = {
		cfgId = 79,
		languageNameID = "flag_Mali",
		icon = "Mali_Flag_icon",
		isShow = 1,
	},
	[80] = {
		cfgId = 80,
		languageNameID = "flag_Mauritania",
		icon = "Mauritania_Flag_icon",
		isShow = 1,
	},
	[81] = {
		cfgId = 81,
		languageNameID = "flag_Micronesia",
		icon = "Micronesia_Flag_icon",
		isShow = 1,
	},
	[82] = {
		cfgId = 82,
		languageNameID = "flag_Mongolia",
		icon = "Mongolia_Flag_icon",
		isShow = 1,
	},
	[83] = {
		cfgId = 83,
		languageNameID = "flag_NewZealand",
		icon = "NewZealand_Flag_icon",
		isShow = 1,
	},
	[84] = {
		cfgId = 84,
		languageNameID = "flag_Nigeria",
		icon = "Nigeria_Flag_icon",
		isShow = 1,
	},
	[85] = {
		cfgId = 85,
		languageNameID = "flag_Niger",
		icon = "Niger_Flag_icon",
		isShow = 1,
	},
	[86] = {
		cfgId = 86,
		languageNameID = "flag_NorthernMacedonia",
		icon = "NorthernMacedonia_Flag_icon",
		isShow = 1,
	},
	[87] = {
		cfgId = 87,
		languageNameID = "flag_NorthKorea",
		icon = "NorthKorea_Flag_icon",
		isShow = 1,
	},
	[88] = {
		cfgId = 88,
		languageNameID = "flag_Norway",
		icon = "Norway_Flag_icon",
		isShow = 1,
	},
	[89] = {
		cfgId = 89,
		languageNameID = "flag_Pakistan",
		icon = "Pakistan_Flag_icon",
		isShow = 1,
	},
	[90] = {
		cfgId = 90,
		languageNameID = "flag_PanamaRepublic",
		icon = "PanamaRepublic_Flag_icon",
		isShow = 1,
	},
	[91] = {
		cfgId = 91,
		languageNameID = "flag_PapuaNewGuinea",
		icon = "PapuaNewGuinea_Flag_icon",
		isShow = 1,
	},
	[92] = {
		cfgId = 92,
		languageNameID = "flag_Peru",
		icon = "Peru_Flag_icon",
		isShow = 1,
	},
	[93] = {
		cfgId = 93,
		languageNameID = "flag_Samoa",
		icon = "Samoa_Flag_icon",
		isShow = 1,
	},
	[94] = {
		cfgId = 94,
		languageNameID = "flag_SlovakRepublic",
		icon = "SlovakRepublic_Flag_icon",
		isShow = 1,
	},
	[95] = {
		cfgId = 95,
		languageNameID = "flag_Somalia",
		icon = "Somalia_Flag_icon",
		isShow = 1,
	},
	[96] = {
		cfgId = 96,
		languageNameID = "flag_SouthAfrica",
		icon = "SouthAfrica_Flag_icon",
		isShow = 1,
	},
	[97] = {
		cfgId = 97,
		languageNameID = "flag_SriLanka",
		icon = "SriLanka_Flag_icon",
		isShow = 1,
	},
	[98] = {
		cfgId = 98,
		languageNameID = "flag_Sudan",
		icon = "Sudan_Flag_icon",
		isShow = 1,
	},
	[99] = {
		cfgId = 99,
		languageNameID = "flag_Sweden",
		icon = "Sweden_Flag_icon",
		isShow = 1,
	},
	[100] = {
		cfgId = 100,
		languageNameID = "flag_Switzerland",
		icon = "Switzerland_Flag_icon",
		isShow = 1,
	},
	[101] = {
		cfgId = 101,
		languageNameID = "flag_Tanzania",
		icon = "Tanzania_Flag_icon",
		isShow = 1,
	},
	[102] = {
		cfgId = 102,
		languageNameID = "flag_Tonga",
		icon = "Tonga_Flag_icon",
		isShow = 1,
	},
	[103] = {
		cfgId = 103,
		languageNameID = "flag_Tunisia",
		icon = "Tunisia_Flag_icon",
		isShow = 1,
	},
	[104] = {
		cfgId = 104,
		languageNameID = "flag_UnitedArabEmirates",
		icon = "UnitedArabEmirates_Flag_icon",
		isShow = 1,
	},
	[105] = {
		cfgId = 105,
		languageNameID = "flag_Uruguay",
		icon = "Uruguay_Flag_icon",
		isShow = 1,
	},
	[106] = {
		cfgId = 106,
		languageNameID = "flag_Uzbekistan",
		icon = "Uzbekistan_Flag_icon",
		isShow = 1,
	},
	[107] = {
		cfgId = 107,
		languageNameID = "flag_Venezuela",
		icon = "Venezuela_Flag_icon",
		isShow = 1,
	},
	[108] = {
		cfgId = 108,
		languageNameID = "flag_Zambia",
		icon = "Zambia_Flag_icon",
		isShow = 1,
	},
}
