-- cfgId                            string                           ""
-- intValue                         int                              ""
-- floatValue                       float                            ""
-- tableValue                       json                             table""
-- stringValue                      string                           string""

return {
	["ItemBagInitSpace"] = {
		cfgId = "ItemBagInitSpace",
		intValue = 50,
		floatValue = 0,
		tableValue = nil,
		stringValue = "",
	},
	["ComposeCount"] = {
		cfgId = "ComposeCount",
		intValue = 3,
		floatValue = 0,
		tableValue = nil,
		stringValue = "",
	},
	["RepairCostPerLife"] = {
		cfgId = "RepairCostPerLife",
		intValue = 1000,
		floatValue = 0,
		tableValue = nil,
		stringValue = "",
	},
	["RepairTimePerLife"] = {
		cfgId = "RepairTimePerLife",
		intValue = 0,
		floatValue = 0,
		tableValue = nil,
		stringValue = "",
	},
	["RepairSpeedUpPerMinute"] = {
		cfgId = "RepairSpeedUpPerMinute",
		intValue = 5000,
		floatValue = 0,
		tableValue = nil,
		stringValue = "",
	},
	["SpeedUpPerMinute"] = {
		cfgId = "SpeedUpPerMinute",
		intValue = 1000,
		floatValue = 0,
		tableValue = nil,
		stringValue = "",
	},
	["ComposeSpeedCostPerHour"] = {
		cfgId = "ComposeSpeedCostPerHour",
		intValue = 2,
		floatValue = 0,
		tableValue = nil,
		stringValue = "",
	},
	["FoundationBattleProtectTime"] = {
		cfgId = "FoundationBattleProtectTime",
		intValue = 0,
		floatValue = 0,
		tableValue = nil,
		stringValue = "",
	},
	["PvpAttackCostStarCoin"] = {
		cfgId = "PvpAttackCostStarCoin",
		intValue = 666,
		floatValue = 0,
		tableValue = nil,
		stringValue = "",
	},
	["PvpLookCostStarCoin"] = {
		cfgId = "PvpLookCostStarCoin",
		intValue = 666,
		floatValue = 0,
		tableValue = nil,
		stringValue = "",
	},
	["AddPvpBattleNumCostMit"] = {
		cfgId = "AddPvpBattleNumCostMit",
		intValue = 10,
		floatValue = 0,
		tableValue = nil,
		stringValue = "",
	},
	["FindPvpPlayersCostStarCoin"] = {
		cfgId = "FindPvpPlayersCostStarCoin",
		intValue = 0,
		floatValue = 0,
		tableValue = {
			[1] = 0,
			[2] = 0,
			[3] = 0,
			[4] = 1000000,
			[5] = 2000000,
			[6] = 3000000,
			[7] = 4000000,
			[8] = 5000000,
			[9] = 6000000,
			[10] = 7000000,
			[11] = 8000000,
			[12] = 9000000,
			[13] = 10000000,
			[14] = 11000000,
			[15] = 12000000,
			[16] = 13000000,
			[17] = 14000000,
			[18] = 15000000,
			[19] = 16000000,
			[20] = 17000000,
		},
		stringValue = "",
	},
	["AchievementBattleInTime"] = {
		cfgId = "AchievementBattleInTime",
		intValue = 60,
		floatValue = 0,
		tableValue = nil,
		stringValue = "",
	},
	["PvpPlunderRatio"] = {
		cfgId = "PvpPlunderRatio",
		intValue = 0,
		floatValue = 0.1,
		tableValue = nil,
		stringValue = "",
	},
	["UnionMemberMax"] = {
		cfgId = "UnionMemberMax",
		intValue = 300,
		floatValue = 0,
		tableValue = nil,
		stringValue = "",
	},
	["UnionMaxTaxRatio"] = {
		cfgId = "UnionMaxTaxRatio",
		intValue = 250,
		floatValue = 0,
		tableValue = nil,
		stringValue = "",
	},
	["UnionOpenVoteTime"] = {
		cfgId = "UnionOpenVoteTime",
		intValue = 0,
		floatValue = 0,
		tableValue = nil,
		stringValue = "",
	},
	["UnionVoteEndTime"] = {
		cfgId = "UnionVoteEndTime",
		intValue = 432000,
		floatValue = 0,
		tableValue = nil,
		stringValue = "",
	},
	["UnionSettleTime"] = {
		cfgId = "UnionSettleTime",
		intValue = 0,
		floatValue = 0,
		tableValue = nil,
		stringValue = "",
	},
	["UnionSettleEndTime"] = {
		cfgId = "UnionSettleEndTime",
		intValue = 259200,
		floatValue = 0,
		tableValue = nil,
		stringValue = "",
	},
	["WorldChatMinBaseLevel"] = {
		cfgId = "WorldChatMinBaseLevel",
		intValue = 5,
		floatValue = 0,
		tableValue = nil,
		stringValue = "",
	},
	["WorldChatNeedMit"] = {
		cfgId = "WorldChatNeedMit",
		intValue = 0,
		floatValue = 0,
		tableValue = nil,
		stringValue = "",
	},
	["ModifyPlayerNameCostHy"] = {
		cfgId = "ModifyPlayerNameCostHy",
		intValue = 100000,
		floatValue = 0,
		tableValue = nil,
		stringValue = "",
	},
	["BuildQueueCount"] = {
		cfgId = "BuildQueueCount",
		intValue = 1,
		floatValue = 0,
		tableValue = nil,
		stringValue = "",
	},
	["ResPlanetProtectTime"] = {
		cfgId = "ResPlanetProtectTime",
		intValue = 1800,
		floatValue = 0,
		tableValue = nil,
		stringValue = "",
	},
	["ChatMaxMsgCount"] = {
		cfgId = "ChatMaxMsgCount",
		intValue = 50,
		floatValue = 0,
		tableValue = nil,
		stringValue = "",
	},
	["FightMaxCostTime"] = {
		cfgId = "FightMaxCostTime",
		intValue = 300,
		floatValue = 0,
		tableValue = nil,
		stringValue = "",
	},
	["InitHeroCfgId"] = {
		cfgId = "InitHeroCfgId",
		intValue = 5000001,
		floatValue = 0,
		tableValue = nil,
		stringValue = "",
	},
	["InitHeroQuality"] = {
		cfgId = "InitHeroQuality",
		intValue = 1,
		floatValue = 0,
		tableValue = nil,
		stringValue = "",
	},
	["InitHeroLevel"] = {
		cfgId = "InitHeroLevel",
		intValue = 1,
		floatValue = 0,
		tableValue = nil,
		stringValue = "",
	},
	["InitWarShipCfgId"] = {
		cfgId = "InitWarShipCfgId",
		intValue = 4000001,
		floatValue = 0,
		tableValue = nil,
		stringValue = "",
	},
	["InitWarShipQuality"] = {
		cfgId = "InitWarShipQuality",
		intValue = 1,
		floatValue = 0,
		tableValue = nil,
		stringValue = "",
	},
	["InitWarShipLevel"] = {
		cfgId = "InitWarShipLevel",
		intValue = 1,
		floatValue = 0,
		tableValue = nil,
		stringValue = "",
	},
	["InitMit"] = {
		cfgId = "InitMit",
		intValue = 0,
		floatValue = 0,
		tableValue = nil,
		stringValue = "",
	},
	["InitStarCoin"] = {
		cfgId = "InitStarCoin",
		intValue = 10000000,
		floatValue = 0,
		tableValue = nil,
		stringValue = "",
	},
	["InitTitanium"] = {
		cfgId = "InitTitanium",
		intValue = 10000000,
		floatValue = 0,
		tableValue = nil,
		stringValue = "",
	},
	["InitGas"] = {
		cfgId = "InitGas",
		intValue = 10000000,
		floatValue = 0,
		tableValue = nil,
		stringValue = "",
	},
	["InitCarboxyl"] = {
		cfgId = "InitCarboxyl",
		intValue = 0,
		floatValue = 0,
		tableValue = nil,
		stringValue = "",
	},
	["InitIce"] = {
		cfgId = "InitIce",
		intValue = 10000000,
		floatValue = 0,
		tableValue = nil,
		stringValue = "",
	},
	["InitTesseract"] = {
		cfgId = "InitTesseract",
		intValue = 150000,
		floatValue = 0,
		tableValue = nil,
		stringValue = "",
	},
	["EnableBattleSameEnemyRepeat"] = {
		cfgId = "EnableBattleSameEnemyRepeat",
		intValue = 1,
		floatValue = 0,
		tableValue = nil,
		stringValue = "",
	},
	["PVPHydroxylBase"] = {
		cfgId = "PVPHydroxylBase",
		intValue = 2000,
		floatValue = 0,
		tableValue = nil,
		stringValue = "",
	},
	["BaseBuildCfgId"] = {
		cfgId = "BaseBuildCfgId",
		intValue = 6010001,
		floatValue = 0,
		tableValue = nil,
		stringValue = "",
	},
	["BlackHoleRepositorieCfgId"] = {
		cfgId = "BlackHoleRepositorieCfgId",
		intValue = 6010010,
		floatValue = 0,
		tableValue = nil,
		stringValue = "",
	},
	["HeroHutCfgId"] = {
		cfgId = "HeroHutCfgId",
		intValue = 6020001,
		floatValue = 0,
		tableValue = nil,
		stringValue = "",
	},
	["HyperSpaceResearchCfgId"] = {
		cfgId = "HyperSpaceResearchCfgId",
		intValue = 6020002,
		floatValue = 0,
		tableValue = nil,
		stringValue = "",
	},
	["GuideIceAward"] = {
		cfgId = "GuideIceAward",
		intValue = 10000,
		floatValue = 0,
		tableValue = nil,
		stringValue = "",
	},
	["GuideStarCoinAward"] = {
		cfgId = "GuideStarCoinAward",
		intValue = 10000,
		floatValue = 0,
		tableValue = nil,
		stringValue = "",
	},
	["ModifyNameUnlockHour"] = {
		cfgId = "ModifyNameUnlockHour",
		intValue = 72,
		floatValue = 0,
		tableValue = nil,
		stringValue = "",
	},
	["BattleNumBuyLimit"] = {
		cfgId = "BattleNumBuyLimit",
		intValue = 10,
		floatValue = 0,
		tableValue = nil,
		stringValue = "",
	},
	["UnionStarCoinLimit"] = {
		cfgId = "UnionStarCoinLimit",
		intValue = 2000000000,
		floatValue = 0,
		tableValue = nil,
		stringValue = "",
	},
	["UnionIceLimit"] = {
		cfgId = "UnionIceLimit",
		intValue = 2000000000,
		floatValue = 0,
		tableValue = nil,
		stringValue = "",
	},
	["UnionGasLimit"] = {
		cfgId = "UnionGasLimit",
		intValue = 2000000000,
		floatValue = 0,
		tableValue = nil,
		stringValue = "",
	},
	["UnionTitaniumLimit"] = {
		cfgId = "UnionTitaniumLimit",
		intValue = 2000000000,
		floatValue = 0,
		tableValue = nil,
		stringValue = "",
	},
	["UnionCarboxylLimit"] = {
		cfgId = "UnionCarboxylLimit",
		intValue = 2100000000,
		floatValue = 0,
		tableValue = nil,
		stringValue = "",
	},
	["UnionInitTechs"] = {
		cfgId = "UnionInitTechs",
		intValue = nil,
		floatValue = nil,
		tableValue = {
		},
		stringValue = "",
	},
	["UnionArmyTeamsLimit"] = {
		cfgId = "UnionArmyTeamsLimit",
		intValue = 50,
		floatValue = nil,
		tableValue = nil,
		stringValue = "",
	},
	["UnionEditArmyLockTime"] = {
		cfgId = "UnionEditArmyLockTime",
		intValue = 600,
		floatValue = nil,
		tableValue = nil,
		stringValue = "",
	},
	["nftTakeBackCD"] = {
		cfgId = "nftTakeBackCD",
		intValue = 0,
		floatValue = nil,
		tableValue = nil,
		stringValue = "",
	},
	["starcoinToPerContribute"] = {
		cfgId = "starcoinToPerContribute",
		intValue = 20000000,
		floatValue = nil,
		tableValue = nil,
		stringValue = "",
	},
	["iceToPerContribute"] = {
		cfgId = "iceToPerContribute",
		intValue = 20000000,
		floatValue = nil,
		tableValue = nil,
		stringValue = "",
	},
	["carboxylToPerContribute"] = {
		cfgId = "carboxylToPerContribute",
		intValue = 20000000,
		floatValue = nil,
		tableValue = nil,
		stringValue = "",
	},
	["titaniumToPerContribute"] = {
		cfgId = "titaniumToPerContribute",
		intValue = 20000000,
		floatValue = nil,
		tableValue = nil,
		stringValue = "",
	},
	["gasToPerContribute"] = {
		cfgId = "gasToPerContribute",
		intValue = 20000000,
		floatValue = nil,
		tableValue = nil,
		stringValue = "",
	},
	["nftMakeContributeCD"] = {
		cfgId = "nftMakeContributeCD",
		intValue = 3600,
		floatValue = nil,
		tableValue = nil,
		stringValue = "",
	},
	["powerToPerContribute"] = {
		cfgId = "powerToPerContribute",
		intValue = 1,
		floatValue = nil,
		tableValue = nil,
		stringValue = "",
	},
	["nftMakeContributeInterval"] = {
		cfgId = "nftMakeContributeInterval",
		intValue = 3600,
		floatValue = nil,
		tableValue = nil,
		stringValue = "",
	},
	["perFleetMakeContribute"] = {
		cfgId = "perFleetMakeContribute",
		intValue = 0,
		floatValue = nil,
		tableValue = nil,
		stringValue = "",
	},
	["unionBattleWarshipCfgId"] = {
		cfgId = "unionBattleWarshipCfgId",
		intValue = 4000001,
		floatValue = nil,
		tableValue = nil,
		stringValue = "",
	},
	["unionBattleWarshipQuality"] = {
		cfgId = "unionBattleWarshipQuality",
		intValue = 1,
		floatValue = nil,
		tableValue = nil,
		stringValue = "",
	},
	["unionBattleWarshipLevel"] = {
		cfgId = "unionBattleWarshipLevel",
		intValue = 1,
		floatValue = nil,
		tableValue = nil,
		stringValue = "",
	},
	["unionBattleBaseSpace"] = {
		cfgId = "unionBattleBaseSpace",
		intValue = 20,
		floatValue = nil,
		tableValue = nil,
		stringValue = "",
	},
	["unionBattleMaxSpace"] = {
		cfgId = "unionBattleMaxSpace",
		intValue = 40,
		floatValue = nil,
		tableValue = nil,
		stringValue = "",
	},
	["unionPositionContributeCD"] = {
		cfgId = "unionPositionContributeCD",
		intValue = 86400,
		floatValue = nil,
		tableValue = nil,
		stringValue = "",
	},
	["GridSettleTime"] = {
		cfgId = "GridSettleTime",
		intValue = 0,
		floatValue = nil,
		tableValue = nil,
		stringValue = "",
	},
	["QuitUnionLimit"] = {
		cfgId = "QuitUnionLimit",
		intValue = 100,
		floatValue = nil,
		tableValue = nil,
		stringValue = "",
	},
	["KickUnionLimit"] = {
		cfgId = "KickUnionLimit",
		intValue = 10,
		floatValue = nil,
		tableValue = nil,
		stringValue = "",
	},
	["StarMakeContributeCD"] = {
		cfgId = "StarMakeContributeCD",
		intValue = 3600,
		floatValue = nil,
		tableValue = nil,
		stringValue = "",
	},
	["GridUnionMax"] = {
		cfgId = "GridUnionMax",
		intValue = 20,
		floatValue = nil,
		tableValue = nil,
		stringValue = "",
	},
	["GridPlayerMax"] = {
		cfgId = "GridPlayerMax",
		intValue = 30,
		floatValue = nil,
		tableValue = nil,
		stringValue = "",
	},
	["RejoinUnionCD"] = {
		cfgId = "RejoinUnionCD",
		intValue = 86400,
		floatValue = nil,
		tableValue = nil,
		stringValue = "",
	},
	["PvpUnlockLevel"] = {
		cfgId = "PvpUnlockLevel",
		intValue = 3,
		floatValue = nil,
		tableValue = nil,
		stringValue = "",
	},
	["LeagueBattleTime"] = {
		cfgId = "LeagueBattleTime",
		intValue = 480,
		floatValue = nil,
		tableValue = nil,
		stringValue = "",
	},
	["LeaguePersonBattleTime"] = {
		cfgId = "LeaguePersonBattleTime",
		intValue = 300,
		floatValue = nil,
		tableValue = nil,
		stringValue = "",
	},
	["RecruitsTrainCD"] = {
		cfgId = "RecruitsTrainCD",
		intValue = 10,
		floatValue = nil,
		tableValue = nil,
		stringValue = "",
	},
	["RecruitsTrainRes"] = {
		cfgId = "RecruitsTrainRes",
		intValue = nil,
		floatValue = nil,
		tableValue = {
			[1] = {
				[1] = 102,
				[2] = 100000,
			},
		},
		stringValue = "",
	},
	["GridProtectTime"] = {
		cfgId = "GridProtectTime",
		intValue = 900,
		floatValue = nil,
		tableValue = nil,
		stringValue = "",
	},
	["GridPersonProtectTime"] = {
		cfgId = "GridPersonProtectTime",
		intValue = 300,
		floatValue = nil,
		tableValue = nil,
		stringValue = "",
	},
	["LeagueWinCostHeroLife"] = {
		cfgId = "LeagueWinCostHeroLife",
		intValue = 2,
		floatValue = nil,
		tableValue = nil,
		stringValue = "",
	},
	["LeagueWinCostWarshipLife"] = {
		cfgId = "LeagueWinCostWarshipLife",
		intValue = 2,
		floatValue = nil,
		tableValue = nil,
		stringValue = "",
	},
	["LeagueFailCostHeroLife"] = {
		cfgId = "LeagueFailCostHeroLife",
		intValue = 10,
		floatValue = nil,
		tableValue = nil,
		stringValue = "",
	},
	["LeagueFailCostWarshipLife"] = {
		cfgId = "LeagueFailCostWarshipLife",
		intValue = 10,
		floatValue = nil,
		tableValue = nil,
		stringValue = "",
	},
	["LeagueDefenceCostLife"] = {
		cfgId = "LeagueDefenceCostLife",
		intValue = 10,
		floatValue = nil,
		tableValue = nil,
		stringValue = "",
	},
	["PvpWinCostHeroLife"] = {
		cfgId = "PvpWinCostHeroLife",
		intValue = 2,
		floatValue = nil,
		tableValue = nil,
		stringValue = "",
	},
	["PvpWinCostWarShipLife"] = {
		cfgId = "PvpWinCostWarShipLife",
		intValue = 2,
		floatValue = nil,
		tableValue = nil,
		stringValue = "",
	},
	["PvpFailCostHeroLife"] = {
		cfgId = "PvpFailCostHeroLife",
		intValue = 10,
		floatValue = nil,
		tableValue = nil,
		stringValue = "",
	},
	["PvpFailCostWarShipLife"] = {
		cfgId = "PvpFailCostWarShipLife",
		intValue = 10,
		floatValue = nil,
		tableValue = nil,
		stringValue = "",
	},
	["InitReserveArmy"] = {
		cfgId = "InitReserveArmy",
		intValue = 50,
		floatValue = nil,
		tableValue = nil,
		stringValue = "",
	},
	["InitBuildLayout"] = {
		cfgId = "InitBuildLayout",
		intValue = 9999,
		floatValue = nil,
		tableValue = nil,
		stringValue = "",
	},
	["NFTMintNeedTime"] = {
		cfgId = "NFTMintNeedTime",
		intValue = 172800,
		floatValue = nil,
		tableValue = nil,
		stringValue = "",
	},
	["NFTMintMaxTime"] = {
		cfgId = "NFTMintMaxTime",
		intValue = 9,
		floatValue = nil,
		tableValue = nil,
		stringValue = "",
	},
	["NFTMintUnlockLeaguePoint"] = {
		cfgId = "NFTMintUnlockLeaguePoint",
		intValue = 0,
		floatValue = nil,
		tableValue = nil,
		stringValue = "",
	},
	["RepairCostPerTime"] = {
		cfgId = "RepairCostPerTime",
		intValue = 10000000,
		floatValue = nil,
		tableValue = nil,
		stringValue = "",
	},
	["personBaseSpace"] = {
		cfgId = "personBaseSpace",
		intValue = 0,
		floatValue = nil,
		tableValue = nil,
		stringValue = "",
	},
	["UnlockSquadBaseLevel"] = {
		cfgId = "UnlockSquadBaseLevel",
		intValue = nil,
		floatValue = nil,
		tableValue = {
			[1] = 0,
			[2] = 0,
			[3] = 10,
			[4] = 15,
			[5] = 20,
		},
		stringValue = "",
	},
	["RebateRate"] = {
		cfgId = "RebateRate",
		intValue = nil,
		floatValue = 0.1,
		tableValue = nil,
		stringValue = "",
	},
	["CreateDAONeedTesseract"] = {
		cfgId = "CreateDAONeedTesseract",
		intValue = 150000,
		floatValue = nil,
		tableValue = nil,
		stringValue = "",
	},
	["PvpWinGainPoint"] = {
		cfgId = "PvpWinGainPoint",
		intValue = 3,
		floatValue = nil,
		tableValue = nil,
		stringValue = "",
	},
	["PvpFailGainPoint"] = {
		cfgId = "PvpFailGainPoint",
		intValue = 1,
		floatValue = nil,
		tableValue = nil,
		stringValue = "",
	},
	["PvpDefenceWinGainPoint"] = {
		cfgId = "PvpDefenceWinGainPoint",
		intValue = 0,
		floatValue = nil,
		tableValue = nil,
		stringValue = "",
	},
	["PvpDefenceFailGainPoint"] = {
		cfgId = "PvpDefenceFailGainPoint",
		intValue = 0,
		floatValue = nil,
		tableValue = nil,
		stringValue = "",
	},
	["PvpDefenceWinGainRes"] = {
		cfgId = "PvpDefenceWinGainRes",
		intValue = nil,
		floatValue = nil,
		tableValue = {
		},
		stringValue = "",
	},
	["PersonCollectLimit"] = {
		cfgId = "PersonCollectLimit",
		intValue = 20,
		floatValue = nil,
		tableValue = nil,
		stringValue = "",
	},
	["GuildCollectLimit"] = {
		cfgId = "GuildCollectLimit",
		intValue = 20,
		floatValue = nil,
		tableValue = nil,
		stringValue = "",
	},
	["GuildMoveCD"] = {
		cfgId = "GuildMoveCD",
		intValue = 259200,
		floatValue = nil,
		tableValue = nil,
		stringValue = "",
	},
	["BaseMakeResCD"] = {
		cfgId = "BaseMakeResCD",
		intValue = 600,
		floatValue = nil,
		tableValue = nil,
		stringValue = "",
	},
	["LeagueMakeResCD"] = {
		cfgId = "LeagueMakeResCD",
		intValue = 900,
		floatValue = nil,
		tableValue = nil,
		stringValue = "",
	},
	["LeagueMakeHYCD"] = {
		cfgId = "LeagueMakeHYCD",
		intValue = 900,
		floatValue = nil,
		tableValue = nil,
		stringValue = "",
	},
	["StarMakePointCD"] = {
		cfgId = "StarMakePointCD",
		intValue = 900,
		floatValue = nil,
		tableValue = nil,
		stringValue = "",
	},
	["GuildDistributeDay"] = {
		cfgId = "GuildDistributeDay",
		intValue = 1,
		floatValue = nil,
		tableValue = nil,
		stringValue = "",
	},
	["GuildDistributeTime"] = {
		cfgId = "GuildDistributeTime",
		intValue = 0,
		floatValue = nil,
		tableValue = nil,
		stringValue = "",
	},
	["enablelevenum"] = {
		cfgId = "enablelevenum",
		intValue = 1,
		floatValue = 0,
		tableValue = nil,
		stringValue = "",
	},
	["GuildBaseSolider"] = {
		cfgId = "GuildBaseSolider",
		intValue = 7101001,
		floatValue = nil,
		tableValue = nil,
		stringValue = "",
	},
	["LeagueHeroBattleCD"] = {
		cfgId = "LeagueHeroBattleCD",
		intValue = 300,
		floatValue = nil,
		tableValue = nil,
		stringValue = "",
	},
	["GuildReserveArmyLimt"] = {
		cfgId = "GuildReserveArmyLimt",
		intValue = 10000,
		floatValue = nil,
		tableValue = nil,
		stringValue = "",
	},
	["GuildReserveArmyCostRes"] = {
		cfgId = "GuildReserveArmyCostRes",
		intValue = nil,
		floatValue = nil,
		tableValue = {
			[1] = {
				[1] = 102,
				[2] = 300000,
			},
		},
		stringValue = "",
	},
	["DrawCardDiscount"] = {
		cfgId = "DrawCardDiscount",
		intValue = nil,
		floatValue = 0.8,
		tableValue = nil,
		stringValue = "",
	},
	["FirstRecharge"] = {
		cfgId = "FirstRecharge",
		intValue = nil,
		floatValue = 0.99,
		tableValue = nil,
		stringValue = "",
	},
	["Recharge"] = {
		cfgId = "Recharge",
		intValue = nil,
		floatValue = 100,
		tableValue = nil,
		stringValue = "",
	},
	["BuilderValue"] = {
		cfgId = "BuilderValue",
		intValue = nil,
		floatValue = nil,
		tableValue = {
			[1] = 107,
			[2] = 3000000,
		},
		stringValue = "",
	},
	["flushShoppingMallNum"] = {
		cfgId = "flushShoppingMallNum",
		intValue = 5,
		floatValue = nil,
		tableValue = nil,
		stringValue = "",
	},
	["UnionSoliderWhiteList"] = {
		cfgId = "UnionSoliderWhiteList",
		intValue = nil,
		floatValue = nil,
		tableValue = {
			[1] = 7101001,
			[2] = 7101003,
			[3] = 7201001,
			[4] = 7201002,
			[5] = 7201004,
			[6] = 7201005,
			[7] = 7201006,
			[8] = 7101008,
			[9] = 7101009,
			[10] = 7101011,
		},
		stringValue = "",
	},
	["UnionDefenseWhiteList"] = {
		cfgId = "UnionDefenseWhiteList",
		intValue = nil,
		floatValue = nil,
		tableValue = {
			[1] = 6031001,
			[2] = 6031002,
			[3] = 6031003,
			[4] = 6031004,
			[5] = 6031005,
			[6] = 6031006,
			[7] = 6031007,
			[8] = 6031008,
			[9] = 6031010,
		},
		stringValue = "",
	},
	["UnionChangeNameCD"] = {
		cfgId = "UnionChangeNameCD",
		intValue = 30,
		floatValue = nil,
		tableValue = nil,
		stringValue = "",
	},
	["UnionChangeNameCost"] = {
		cfgId = "UnionChangeNameCost",
		intValue = nil,
		floatValue = nil,
		tableValue = {
			[1] = 107,
			[2] = 2000000,
		},
		stringValue = "",
	},
	["FlushShoppingMallCost"] = {
		cfgId = "FlushShoppingMallCost",
		intValue = 0,
		floatValue = 0,
		tableValue = {
			[1] = {
				[1] = 107,
				[2] = 100000,
			},
		},
		stringValue = "",
	},
	["WithdrawCD"] = {
		cfgId = "WithdrawCD",
		intValue = 2592000,
		floatValue = nil,
		tableValue = nil,
		stringValue = "",
	},
	["WithdrawMinHYT"] = {
		cfgId = "WithdrawMinHYT",
		intValue = 3000000,
		floatValue = nil,
		tableValue = nil,
		stringValue = "",
	},
	["WithdrawMinMIT"] = {
		cfgId = "WithdrawMinMIT",
		intValue = 10000,
		floatValue = nil,
		tableValue = nil,
		stringValue = "",
	},
	["UnlockDiscount"] = {
		cfgId = "UnlockDiscount",
		intValue = nil,
		floatValue = 0.85,
		tableValue = nil,
		stringValue = "",
	},
	["UnionTechLevelUpMaxCount"] = {
		cfgId = "UnionTechLevelUpMaxCount",
		intValue = 1,
		floatValue = nil,
		tableValue = nil,
		stringValue = "",
	},
	["UnionModTechLevelUpMaxCount"] = {
		cfgId = "UnionModTechLevelUpMaxCount",
		intValue = 1,
		floatValue = nil,
		tableValue = nil,
		stringValue = "",
	},
	["GuildContributeRatio"] = {
		cfgId = "GuildContributeRatio",
		intValue = nil,
		floatValue = 0.5,
		tableValue = nil,
		stringValue = "",
	},
	["DamageToPerConquest"] = {
		cfgId = "DamageToPerConquest",
		intValue = 10000,
		floatValue = nil,
		tableValue = nil,
		stringValue = "",
	},
	["OneKeyUnlockCost"] = {
		cfgId = "OneKeyUnlockCost",
		intValue = nil,
		floatValue = nil,
		tableValue = nil,
		stringValue = "gb.tesseract.9999",
	},
	["PvpMatchPoint"] = {
		cfgId = "PvpMatchPoint",
		intValue = 20,
		floatValue = nil,
		tableValue = nil,
		stringValue = "",
	},
	["PvpMatchLevel"] = {
		cfgId = "PvpMatchLevel",
		intValue = 5,
		floatValue = nil,
		tableValue = nil,
		stringValue = "",
	},
	["InitDefence"] = {
		cfgId = "InitDefence",
		intValue = nil,
		floatValue = nil,
		tableValue = {
			[1] = 6030011,
			[2] = 1,
			[3] = 1,
		},
		stringValue = "",
	},
	["HyAbandonGridCD"] = {
		cfgId = "HyAbandonGridCD",
		intValue = 1500,
		floatValue = nil,
		tableValue = nil,
		stringValue = "",
	},
	["ResAbandonGridCD"] = {
		cfgId = "ResAbandonGridCD",
		intValue = 1500,
		floatValue = nil,
		tableValue = nil,
		stringValue = "",
	},
	["PvpSearchCount"] = {
		cfgId = "PvpSearchCount",
		intValue = 10,
		floatValue = nil,
		tableValue = nil,
		stringValue = "",
	},
	["UpdateSkillUIMaxTime"] = {
		cfgId = "UpdateSkillUIMaxTime",
		intValue = nil,
		floatValue = 0.2,
		tableValue = nil,
		stringValue = "",
	},
	["HQBagMax"] = {
		cfgId = "HQBagMax",
		intValue = 100,
		floatValue = nil,
		tableValue = nil,
		stringValue = "",
	},
	["SellingPrice"] = {
		cfgId = "SellingPrice",
		intValue = nil,
		floatValue = nil,
		tableValue = {
			[1] = 1500000,
			[2] = 3000000,
			[3] = 5000000,
		},
		stringValue = "",
	},
}
