-- index                            int                              ""
-- cfgId                            int                              ""
-- type                             int                              ""
-- resName                          string                           ""
-- model                            string                           ""

return {
	[1] = {
		index = 1,
		cfgId = 1,
		type = 9,
		resName = "PVEicon",
		model = "PVEicon",
	},
	[2] = {
		index = 2,
		cfgId = 2,
		type = 9,
		resName = "SmallPlane",
		model = "SmallPlane",
	},
	[3] = {
		index = 3,
		cfgId = 3,
		type = 9,
		resName = "Arsenal",
		model = "Buller_Arsenal",
	},
	[4] = {
		index = 4,
		cfgId = 4,
		type = 9,
		resName = "ShipAirship",
		model = "ShipAirship",
	},
	[5] = {
		index = 5,
		cfgId = 5,
		type = 9,
		resName = "TalusAirship",
		model = "TalusAirship",
	},
	[6] = {
		index = 6,
		cfgId = 6,
		type = 9,
		resName = "ScougeAirship",
		model = "ScougeAirship",
	},
	[7] = {
		index = 7,
		cfgId = 7,
		type = 9,
		resName = "CentraAirship",
		model = "CentraAirship",
	},
	[8] = {
		index = 8,
		cfgId = 8,
		type = 9,
		resName = "EndariAirship",
		model = "EndariAirship",
	},
	[9] = {
		index = 9,
		cfgId = 9,
		type = 9,
		resName = "CapsuleCabin",
		model = "CapsuleCabin",
	},
	[10] = {
		index = 10,
		cfgId = 10,
		type = 9,
		resName = "Com_B3_1",
		model = "Com_B3_1",
	},
	[11] = {
		index = 11,
		cfgId = 11,
		type = 9,
		resName = "Com_B3_1",
		model = "Com_B3_1",
	},
	[12] = {
		index = 12,
		cfgId = 12,
		type = 9,
		resName = "Gold_A3_1",
		model = "Gold_A3_1",
	},
	[13] = {
		index = 13,
		cfgId = 13,
		type = 9,
		resName = "Gold_A3_1",
		model = "Gold_A3_1",
	},
	[14] = {
		index = 14,
		cfgId = 14,
		type = 9,
		resName = "Gold_A3_2",
		model = "Gold_A3_2",
	},
	[15] = {
		index = 15,
		cfgId = 15,
		type = 9,
		resName = "Gold_A3_2",
		model = "Gold_A3_2",
	},
	[16] = {
		index = 16,
		cfgId = 16,
		type = 9,
		resName = "Gold_B3_1",
		model = "Gold_B3_1",
	},
	[17] = {
		index = 17,
		cfgId = 17,
		type = 9,
		resName = "Gold_B3_1",
		model = "Gold_B3_1",
	},
	[18] = {
		index = 18,
		cfgId = 18,
		type = 9,
		resName = "Gold_B3_2",
		model = "Gold_B3_2",
	},
	[19] = {
		index = 19,
		cfgId = 19,
		type = 9,
		resName = "Gold_B3_2",
		model = "Gold_B3_2",
	},
	[20] = {
		index = 20,
		cfgId = 20,
		type = 9,
		resName = "Map_A3_1",
		model = "Map_A3_1",
	},
	[21] = {
		index = 21,
		cfgId = 21,
		type = 9,
		resName = "Map_A3_1",
		model = "Map_A3_1",
	},
	[22] = {
		index = 22,
		cfgId = 22,
		type = 9,
		resName = "Com_C3_1",
		model = "Com_C3_1",
	},
	[23] = {
		index = 23,
		cfgId = 23,
		type = 9,
		resName = "Com_C3_1",
		model = "Com_C3_1",
	},
	[24] = {
		index = 24,
		cfgId = 24,
		type = 9,
		resName = "Com_C3_2",
		model = "Com_C3_2",
	},
	[25] = {
		index = 25,
		cfgId = 25,
		type = 9,
		resName = "Com_C3_2",
		model = "Com_C3_2",
	},
	[26] = {
		index = 26,
		cfgId = 26,
		type = 9,
		resName = "Gas_A4_3",
		model = "Gas_A4_3",
	},
	[27] = {
		index = 27,
		cfgId = 27,
		type = 9,
		resName = "Gas_A4_3",
		model = "Gas_A4_3",
	},
	[28] = {
		index = 28,
		cfgId = 28,
		type = 9,
		resName = "Gas_A4_4",
		model = "Gas_A4_4",
	},
	[29] = {
		index = 29,
		cfgId = 29,
		type = 9,
		resName = "Gas_A4_4",
		model = "Gas_A4_4",
	},
	[30] = {
		index = 30,
		cfgId = 30,
		type = 9,
		resName = "Gas_B4_1",
		model = "Gas_B4_1",
	},
	[31] = {
		index = 31,
		cfgId = 31,
		type = 9,
		resName = "Gas_B4_1",
		model = "Gas_B4_1",
	},
	[32] = {
		index = 32,
		cfgId = 32,
		type = 9,
		resName = "Gas_B4_2",
		model = "Gas_B4_2",
	},
	[33] = {
		index = 33,
		cfgId = 33,
		type = 9,
		resName = "Gas_B4_2",
		model = "Gas_B4_2",
	},
	[34] = {
		index = 34,
		cfgId = 34,
		type = 9,
		resName = "Map_A4_1",
		model = "Map_A4_1",
	},
	[35] = {
		index = 35,
		cfgId = 35,
		type = 9,
		resName = "Map_A4_1",
		model = "Map_A4_1",
	},
	[36] = {
		index = 36,
		cfgId = 36,
		type = 9,
		resName = "Com_C4_1",
		model = "Com_C4_1",
	},
	[37] = {
		index = 37,
		cfgId = 37,
		type = 9,
		resName = "Com_C4_1",
		model = "Com_C4_1",
	},
	[38] = {
		index = 38,
		cfgId = 38,
		type = 9,
		resName = "Com_C4_2",
		model = "Com_C4_2",
	},
	[39] = {
		index = 39,
		cfgId = 39,
		type = 9,
		resName = "Com_C4_2",
		model = "Com_C4_2",
	},
	[40] = {
		index = 40,
		cfgId = 40,
		type = 9,
		resName = "Com_C4_3",
		model = "Com_C4_3",
	},
	[41] = {
		index = 41,
		cfgId = 41,
		type = 9,
		resName = "Com_C4_3",
		model = "Com_C4_3",
	},
	[42] = {
		index = 42,
		cfgId = 42,
		type = 9,
		resName = "Com_B5_1",
		model = "Com_B5_1",
	},
	[43] = {
		index = 43,
		cfgId = 43,
		type = 9,
		resName = "Com_B5_1",
		model = "Com_B5_1",
	},
	[44] = {
		index = 44,
		cfgId = 44,
		type = 9,
		resName = "Com_B5_2",
		model = "Com_B5_2",
	},
	[45] = {
		index = 45,
		cfgId = 45,
		type = 9,
		resName = "Com_B5_2",
		model = "Com_B5_2",
	},
	[46] = {
		index = 46,
		cfgId = 46,
		type = 9,
		resName = "Metal_A5_1",
		model = "Metal_A5_1",
	},
	[47] = {
		index = 47,
		cfgId = 47,
		type = 9,
		resName = "Metal_A5_1",
		model = "Metal_A5_1",
	},
	[48] = {
		index = 48,
		cfgId = 48,
		type = 9,
		resName = "Metal_A5_2",
		model = "Metal_A5_2",
	},
	[49] = {
		index = 49,
		cfgId = 49,
		type = 9,
		resName = "Metal_A5_2",
		model = "Metal_A5_2",
	},
	[50] = {
		index = 50,
		cfgId = 50,
		type = 9,
		resName = "Com_C5_1",
		model = "Com_C5_1",
	},
	[51] = {
		index = 51,
		cfgId = 51,
		type = 9,
		resName = "Com_C5_1",
		model = "Com_C5_1",
	},
	[52] = {
		index = 52,
		cfgId = 52,
		type = 9,
		resName = "Ice_A6_1",
		model = "Ice_A6_1",
	},
	[53] = {
		index = 53,
		cfgId = 53,
		type = 9,
		resName = "Ice_A6_1",
		model = "Ice_A6_1",
	},
	[54] = {
		index = 54,
		cfgId = 54,
		type = 9,
		resName = "Ice_A6_2",
		model = "Ice_A6_2",
	},
	[55] = {
		index = 55,
		cfgId = 55,
		type = 9,
		resName = "Ice_A6_2",
		model = "Ice_A6_2",
	},
	[56] = {
		index = 56,
		cfgId = 56,
		type = 9,
		resName = "Ice_B6_1",
		model = "Ice_B6_1",
	},
	[57] = {
		index = 57,
		cfgId = 57,
		type = 9,
		resName = "Ice_B6_1",
		model = "Ice_B6_1",
	},
	[58] = {
		index = 58,
		cfgId = 58,
		type = 9,
		resName = "Com_C8_1",
		model = "Com_C8_1",
	},
	[59] = {
		index = 59,
		cfgId = 59,
		type = 9,
		resName = "Com_C8_1",
		model = "Com_C8_1",
	},
	[60] = {
		index = 60,
		cfgId = 60,
		type = 9,
		resName = "Com_C8B_1",
		model = "Com_C8B_1",
	},
	[61] = {
		index = 61,
		cfgId = 61,
		type = 9,
		resName = "Com_C8B_1",
		model = "Com_C8B_1",
	},
	[62] = {
		index = 62,
		cfgId = 62,
		type = 9,
		resName = "Com_C8x4R_1",
		model = "Com_C8x4R_1",
	},
	[63] = {
		index = 63,
		cfgId = 63,
		type = 9,
		resName = "Com_C8x4R_1",
		model = "Com_C8x4R_1",
	},
}
