-- index                            int                              ""
-- cfgId                            int                              ""ID
-- level                            int                              ""
-- startRatio                       int                              ""
-- maxRatio                         int                              ""
-- mitPerRatio                      int                              ""mit
-- maxHp                            int                              ""
-- atk                              int                              ""
-- levelUpNeedTick                  int                              ""("")
-- levelUpNeedStarCoin              int                              ""
-- levelUpNeedIce                   int                              ""
-- levelUpNeedCarboxyl              int                              ""
-- levelUpNeedTitanium              int                              ""
-- levelUpNeedGas                   int                              ""
-- showAttr                         json                             ""，""attribute""

return {
	[1] = {
		index = 1,
		cfgId = 4101001,
		level = 0,
		startRatio = 100,
		maxRatio = 100,
		mitPerRatio = 3,
		maxHp = 0,
		atk = 0,
		levelUpNeedTick = 60,
		levelUpNeedStarCoin = 20,
		levelUpNeedIce = 20,
		levelUpNeedCarboxyl = 20,
		levelUpNeedTitanium = 20,
		levelUpNeedGas = 20,
		showAttr = {
			[1] = {
				[1] = "maxHp",
				[2] = "atk",
			},
		},
	},
	[2] = {
		index = 2,
		cfgId = 4101001,
		level = 1,
		startRatio = 90,
		maxRatio = 100,
		mitPerRatio = 3,
		maxHp = 30,
		atk = 30,
		levelUpNeedTick = 60,
		levelUpNeedStarCoin = 20,
		levelUpNeedIce = 20,
		levelUpNeedCarboxyl = 20,
		levelUpNeedTitanium = 20,
		levelUpNeedGas = 20,
		showAttr = {
			[1] = {
				[1] = "maxHp",
				[2] = "atk",
			},
		},
	},
	[3] = {
		index = 3,
		cfgId = 4101001,
		level = 2,
		startRatio = 80,
		maxRatio = 90,
		mitPerRatio = 3,
		maxHp = 60,
		atk = 60,
		levelUpNeedTick = 60,
		levelUpNeedStarCoin = 20,
		levelUpNeedIce = 20,
		levelUpNeedCarboxyl = 20,
		levelUpNeedTitanium = 20,
		levelUpNeedGas = 20,
		showAttr = {
			[1] = {
				[1] = "maxHp",
				[2] = "atk",
			},
		},
	},
	[4] = {
		index = 4,
		cfgId = 4101001,
		level = 3,
		startRatio = 70,
		maxRatio = 80,
		mitPerRatio = 3,
		maxHp = 90,
		atk = 90,
		levelUpNeedTick = 60,
		levelUpNeedStarCoin = 20,
		levelUpNeedIce = 20,
		levelUpNeedCarboxyl = 20,
		levelUpNeedTitanium = 20,
		levelUpNeedGas = 20,
		showAttr = {
			[1] = {
				[1] = "maxHp",
				[2] = "atk",
			},
		},
	},
	[5] = {
		index = 5,
		cfgId = 4101001,
		level = 4,
		startRatio = 60,
		maxRatio = 70,
		mitPerRatio = 3,
		maxHp = 120,
		atk = 120,
		levelUpNeedTick = 60,
		levelUpNeedStarCoin = 20,
		levelUpNeedIce = 20,
		levelUpNeedCarboxyl = 20,
		levelUpNeedTitanium = 20,
		levelUpNeedGas = 20,
		showAttr = {
			[1] = {
				[1] = "maxHp",
				[2] = "atk",
			},
		},
	},
	[6] = {
		index = 6,
		cfgId = 4101001,
		level = 5,
		startRatio = 50,
		maxRatio = 60,
		mitPerRatio = 3,
		maxHp = 150,
		atk = 150,
		levelUpNeedTick = 60,
		levelUpNeedStarCoin = 20,
		levelUpNeedIce = 20,
		levelUpNeedCarboxyl = 20,
		levelUpNeedTitanium = 20,
		levelUpNeedGas = 20,
		showAttr = {
			[1] = {
				[1] = "maxHp",
				[2] = "atk",
			},
		},
	},
	[7] = {
		index = 7,
		cfgId = 4101001,
		level = 6,
		startRatio = 40,
		maxRatio = 50,
		mitPerRatio = 3,
		maxHp = 180,
		atk = 180,
		levelUpNeedTick = 60,
		levelUpNeedStarCoin = 20,
		levelUpNeedIce = 20,
		levelUpNeedCarboxyl = 20,
		levelUpNeedTitanium = 20,
		levelUpNeedGas = 20,
		showAttr = {
			[1] = {
				[1] = "maxHp",
				[2] = "atk",
			},
		},
	},
	[8] = {
		index = 8,
		cfgId = 4101002,
		level = 0,
		startRatio = 100,
		maxRatio = 100,
		mitPerRatio = 3,
		maxHp = 0,
		atk = 0,
		levelUpNeedTick = 60,
		levelUpNeedStarCoin = 20,
		levelUpNeedIce = 20,
		levelUpNeedCarboxyl = 20,
		levelUpNeedTitanium = 20,
		levelUpNeedGas = 20,
		showAttr = {
			[1] = {
				[1] = "maxHp",
				[2] = "atk",
			},
		},
	},
	[9] = {
		index = 9,
		cfgId = 4101002,
		level = 1,
		startRatio = 90,
		maxRatio = 100,
		mitPerRatio = 3,
		maxHp = 30,
		atk = 30,
		levelUpNeedTick = 60,
		levelUpNeedStarCoin = 20,
		levelUpNeedIce = 20,
		levelUpNeedCarboxyl = 20,
		levelUpNeedTitanium = 20,
		levelUpNeedGas = 20,
		showAttr = {
			[1] = {
				[1] = "maxHp",
				[2] = "atk",
			},
		},
	},
	[10] = {
		index = 10,
		cfgId = 4101002,
		level = 2,
		startRatio = 80,
		maxRatio = 90,
		mitPerRatio = 3,
		maxHp = 60,
		atk = 60,
		levelUpNeedTick = 60,
		levelUpNeedStarCoin = 20,
		levelUpNeedIce = 20,
		levelUpNeedCarboxyl = 20,
		levelUpNeedTitanium = 20,
		levelUpNeedGas = 20,
		showAttr = {
			[1] = {
				[1] = "maxHp",
				[2] = "atk",
			},
		},
	},
	[11] = {
		index = 11,
		cfgId = 4101002,
		level = 3,
		startRatio = 70,
		maxRatio = 80,
		mitPerRatio = 3,
		maxHp = 90,
		atk = 90,
		levelUpNeedTick = 60,
		levelUpNeedStarCoin = 20,
		levelUpNeedIce = 20,
		levelUpNeedCarboxyl = 20,
		levelUpNeedTitanium = 20,
		levelUpNeedGas = 20,
		showAttr = {
			[1] = {
				[1] = "maxHp",
				[2] = "atk",
			},
		},
	},
	[12] = {
		index = 12,
		cfgId = 4101002,
		level = 4,
		startRatio = 60,
		maxRatio = 70,
		mitPerRatio = 3,
		maxHp = 120,
		atk = 120,
		levelUpNeedTick = 60,
		levelUpNeedStarCoin = 20,
		levelUpNeedIce = 20,
		levelUpNeedCarboxyl = 20,
		levelUpNeedTitanium = 20,
		levelUpNeedGas = 20,
		showAttr = {
			[1] = {
				[1] = "maxHp",
				[2] = "atk",
			},
		},
	},
	[13] = {
		index = 13,
		cfgId = 4101002,
		level = 5,
		startRatio = 50,
		maxRatio = 60,
		mitPerRatio = 3,
		maxHp = 150,
		atk = 150,
		levelUpNeedTick = 60,
		levelUpNeedStarCoin = 20,
		levelUpNeedIce = 20,
		levelUpNeedCarboxyl = 20,
		levelUpNeedTitanium = 20,
		levelUpNeedGas = 20,
		showAttr = {
			[1] = {
				[1] = "maxHp",
				[2] = "atk",
			},
		},
	},
	[14] = {
		index = 14,
		cfgId = 4101002,
		level = 6,
		startRatio = 40,
		maxRatio = 50,
		mitPerRatio = 3,
		maxHp = 180,
		atk = 180,
		levelUpNeedTick = 60,
		levelUpNeedStarCoin = 20,
		levelUpNeedIce = 20,
		levelUpNeedCarboxyl = 20,
		levelUpNeedTitanium = 20,
		levelUpNeedGas = 20,
		showAttr = {
			[1] = {
				[1] = "maxHp",
				[2] = "atk",
			},
		},
	},
	[15] = {
		index = 15,
		cfgId = 4101003,
		level = 0,
		startRatio = 100,
		maxRatio = 100,
		mitPerRatio = 3,
		maxHp = 0,
		atk = 0,
		levelUpNeedTick = 60,
		levelUpNeedStarCoin = 20,
		levelUpNeedIce = 20,
		levelUpNeedCarboxyl = 20,
		levelUpNeedTitanium = 20,
		levelUpNeedGas = 20,
		showAttr = {
			[1] = {
				[1] = "maxHp",
				[2] = "atk",
			},
		},
	},
	[16] = {
		index = 16,
		cfgId = 4101003,
		level = 1,
		startRatio = 90,
		maxRatio = 100,
		mitPerRatio = 3,
		maxHp = 30,
		atk = 30,
		levelUpNeedTick = 60,
		levelUpNeedStarCoin = 20,
		levelUpNeedIce = 20,
		levelUpNeedCarboxyl = 20,
		levelUpNeedTitanium = 20,
		levelUpNeedGas = 20,
		showAttr = {
			[1] = {
				[1] = "maxHp",
				[2] = "atk",
			},
		},
	},
	[17] = {
		index = 17,
		cfgId = 4101003,
		level = 2,
		startRatio = 80,
		maxRatio = 90,
		mitPerRatio = 3,
		maxHp = 60,
		atk = 60,
		levelUpNeedTick = 60,
		levelUpNeedStarCoin = 20,
		levelUpNeedIce = 20,
		levelUpNeedCarboxyl = 20,
		levelUpNeedTitanium = 20,
		levelUpNeedGas = 20,
		showAttr = {
			[1] = {
				[1] = "maxHp",
				[2] = "atk",
			},
		},
	},
	[18] = {
		index = 18,
		cfgId = 4101003,
		level = 3,
		startRatio = 70,
		maxRatio = 80,
		mitPerRatio = 3,
		maxHp = 90,
		atk = 90,
		levelUpNeedTick = 60,
		levelUpNeedStarCoin = 20,
		levelUpNeedIce = 20,
		levelUpNeedCarboxyl = 20,
		levelUpNeedTitanium = 20,
		levelUpNeedGas = 20,
		showAttr = {
			[1] = {
				[1] = "maxHp",
				[2] = "atk",
			},
		},
	},
	[19] = {
		index = 19,
		cfgId = 4101003,
		level = 4,
		startRatio = 60,
		maxRatio = 70,
		mitPerRatio = 3,
		maxHp = 120,
		atk = 120,
		levelUpNeedTick = 60,
		levelUpNeedStarCoin = 20,
		levelUpNeedIce = 20,
		levelUpNeedCarboxyl = 20,
		levelUpNeedTitanium = 20,
		levelUpNeedGas = 20,
		showAttr = {
			[1] = {
				[1] = "maxHp",
				[2] = "atk",
			},
		},
	},
	[20] = {
		index = 20,
		cfgId = 4101003,
		level = 5,
		startRatio = 50,
		maxRatio = 60,
		mitPerRatio = 3,
		maxHp = 150,
		atk = 150,
		levelUpNeedTick = 60,
		levelUpNeedStarCoin = 20,
		levelUpNeedIce = 20,
		levelUpNeedCarboxyl = 20,
		levelUpNeedTitanium = 20,
		levelUpNeedGas = 20,
		showAttr = {
			[1] = {
				[1] = "maxHp",
				[2] = "atk",
			},
		},
	},
	[21] = {
		index = 21,
		cfgId = 4101003,
		level = 6,
		startRatio = 40,
		maxRatio = 50,
		mitPerRatio = 3,
		maxHp = 180,
		atk = 180,
		levelUpNeedTick = 60,
		levelUpNeedStarCoin = 20,
		levelUpNeedIce = 20,
		levelUpNeedCarboxyl = 20,
		levelUpNeedTitanium = 20,
		levelUpNeedGas = 20,
		showAttr = {
			[1] = {
				[1] = "maxHp",
				[2] = "atk",
			},
		},
	},
	[22] = {
		index = 22,
		cfgId = 4101004,
		level = 0,
		startRatio = 100,
		maxRatio = 100,
		mitPerRatio = 3,
		maxHp = 0,
		atk = 0,
		levelUpNeedTick = 60,
		levelUpNeedStarCoin = 20,
		levelUpNeedIce = 20,
		levelUpNeedCarboxyl = 20,
		levelUpNeedTitanium = 20,
		levelUpNeedGas = 20,
		showAttr = {
			[1] = {
				[1] = "maxHp",
				[2] = "atk",
			},
		},
	},
	[23] = {
		index = 23,
		cfgId = 4101004,
		level = 1,
		startRatio = 90,
		maxRatio = 100,
		mitPerRatio = 3,
		maxHp = 30,
		atk = 30,
		levelUpNeedTick = 60,
		levelUpNeedStarCoin = 20,
		levelUpNeedIce = 20,
		levelUpNeedCarboxyl = 20,
		levelUpNeedTitanium = 20,
		levelUpNeedGas = 20,
		showAttr = {
			[1] = {
				[1] = "maxHp",
				[2] = "atk",
			},
		},
	},
	[24] = {
		index = 24,
		cfgId = 4101004,
		level = 2,
		startRatio = 80,
		maxRatio = 90,
		mitPerRatio = 3,
		maxHp = 60,
		atk = 60,
		levelUpNeedTick = 60,
		levelUpNeedStarCoin = 20,
		levelUpNeedIce = 20,
		levelUpNeedCarboxyl = 20,
		levelUpNeedTitanium = 20,
		levelUpNeedGas = 20,
		showAttr = {
			[1] = {
				[1] = "maxHp",
				[2] = "atk",
			},
		},
	},
	[25] = {
		index = 25,
		cfgId = 4101004,
		level = 3,
		startRatio = 70,
		maxRatio = 80,
		mitPerRatio = 3,
		maxHp = 90,
		atk = 90,
		levelUpNeedTick = 60,
		levelUpNeedStarCoin = 20,
		levelUpNeedIce = 20,
		levelUpNeedCarboxyl = 20,
		levelUpNeedTitanium = 20,
		levelUpNeedGas = 20,
		showAttr = {
			[1] = {
				[1] = "maxHp",
				[2] = "atk",
			},
		},
	},
	[26] = {
		index = 26,
		cfgId = 4101004,
		level = 4,
		startRatio = 60,
		maxRatio = 70,
		mitPerRatio = 3,
		maxHp = 120,
		atk = 120,
		levelUpNeedTick = 60,
		levelUpNeedStarCoin = 20,
		levelUpNeedIce = 20,
		levelUpNeedCarboxyl = 20,
		levelUpNeedTitanium = 20,
		levelUpNeedGas = 20,
		showAttr = {
			[1] = {
				[1] = "maxHp",
				[2] = "atk",
			},
		},
	},
	[27] = {
		index = 27,
		cfgId = 4101004,
		level = 5,
		startRatio = 50,
		maxRatio = 60,
		mitPerRatio = 3,
		maxHp = 150,
		atk = 150,
		levelUpNeedTick = 60,
		levelUpNeedStarCoin = 20,
		levelUpNeedIce = 20,
		levelUpNeedCarboxyl = 20,
		levelUpNeedTitanium = 20,
		levelUpNeedGas = 20,
		showAttr = {
			[1] = {
				[1] = "maxHp",
				[2] = "atk",
			},
		},
	},
	[28] = {
		index = 28,
		cfgId = 4101004,
		level = 6,
		startRatio = 40,
		maxRatio = 50,
		mitPerRatio = 3,
		maxHp = 180,
		atk = 180,
		levelUpNeedTick = 60,
		levelUpNeedStarCoin = 20,
		levelUpNeedIce = 20,
		levelUpNeedCarboxyl = 20,
		levelUpNeedTitanium = 20,
		levelUpNeedGas = 20,
		showAttr = {
			[1] = {
				[1] = "maxHp",
				[2] = "atk",
			},
		},
	},
	[29] = {
		index = 29,
		cfgId = 4101005,
		level = 0,
		startRatio = 100,
		maxRatio = 100,
		mitPerRatio = 3,
		maxHp = 0,
		atk = 0,
		levelUpNeedTick = 60,
		levelUpNeedStarCoin = 20,
		levelUpNeedIce = 20,
		levelUpNeedCarboxyl = 20,
		levelUpNeedTitanium = 20,
		levelUpNeedGas = 20,
		showAttr = {
			[1] = {
				[1] = "maxHp",
				[2] = "atk",
			},
		},
	},
	[30] = {
		index = 30,
		cfgId = 4101005,
		level = 1,
		startRatio = 90,
		maxRatio = 100,
		mitPerRatio = 3,
		maxHp = 30,
		atk = 30,
		levelUpNeedTick = 60,
		levelUpNeedStarCoin = 20,
		levelUpNeedIce = 20,
		levelUpNeedCarboxyl = 20,
		levelUpNeedTitanium = 20,
		levelUpNeedGas = 20,
		showAttr = {
			[1] = {
				[1] = "maxHp",
				[2] = "atk",
			},
		},
	},
	[31] = {
		index = 31,
		cfgId = 4101005,
		level = 2,
		startRatio = 80,
		maxRatio = 90,
		mitPerRatio = 3,
		maxHp = 60,
		atk = 60,
		levelUpNeedTick = 60,
		levelUpNeedStarCoin = 20,
		levelUpNeedIce = 20,
		levelUpNeedCarboxyl = 20,
		levelUpNeedTitanium = 20,
		levelUpNeedGas = 20,
		showAttr = {
			[1] = {
				[1] = "maxHp",
				[2] = "atk",
			},
		},
	},
	[32] = {
		index = 32,
		cfgId = 4101005,
		level = 3,
		startRatio = 70,
		maxRatio = 80,
		mitPerRatio = 3,
		maxHp = 90,
		atk = 90,
		levelUpNeedTick = 60,
		levelUpNeedStarCoin = 20,
		levelUpNeedIce = 20,
		levelUpNeedCarboxyl = 20,
		levelUpNeedTitanium = 20,
		levelUpNeedGas = 20,
		showAttr = {
			[1] = {
				[1] = "maxHp",
				[2] = "atk",
			},
		},
	},
	[33] = {
		index = 33,
		cfgId = 4101005,
		level = 4,
		startRatio = 60,
		maxRatio = 70,
		mitPerRatio = 3,
		maxHp = 120,
		atk = 120,
		levelUpNeedTick = 60,
		levelUpNeedStarCoin = 20,
		levelUpNeedIce = 20,
		levelUpNeedCarboxyl = 20,
		levelUpNeedTitanium = 20,
		levelUpNeedGas = 20,
		showAttr = {
			[1] = {
				[1] = "maxHp",
				[2] = "atk",
			},
		},
	},
	[34] = {
		index = 34,
		cfgId = 4101005,
		level = 5,
		startRatio = 50,
		maxRatio = 60,
		mitPerRatio = 3,
		maxHp = 150,
		atk = 150,
		levelUpNeedTick = 60,
		levelUpNeedStarCoin = 20,
		levelUpNeedIce = 20,
		levelUpNeedCarboxyl = 20,
		levelUpNeedTitanium = 20,
		levelUpNeedGas = 20,
		showAttr = {
			[1] = {
				[1] = "maxHp",
				[2] = "atk",
			},
		},
	},
	[35] = {
		index = 35,
		cfgId = 4101005,
		level = 6,
		startRatio = 40,
		maxRatio = 50,
		mitPerRatio = 3,
		maxHp = 180,
		atk = 180,
		levelUpNeedTick = 60,
		levelUpNeedStarCoin = 20,
		levelUpNeedIce = 20,
		levelUpNeedCarboxyl = 20,
		levelUpNeedTitanium = 20,
		levelUpNeedGas = 20,
		showAttr = {
			[1] = {
				[1] = "maxHp",
				[2] = "atk",
			},
		},
	},
}
