-- index                            int                              ""
-- cfgId                            int                              ""(1.""（""），""3 2.""，""3 3.PVP""，""3 4.""（""），""5""，""4 5.""（""），""5""，""5 6.""（""），""5""，""5 7.PVP""，""7 8.""（""，""），""5""，""8 9.""MIT""，""9 10.""，""10)
-- unlockLevel                      int                              ""
-- level                            int                              ""
-- name                             string                           ""
-- targetValue                      int                              ""
-- targetCfgId                      int                              ""
-- showStar                         int                              ""(cfgId""showStar"")
-- totalStar                        int                              ""
-- nextIndex                        int                              ""(""0"")
-- reward                           json                             ""MIT
-- desc                             string                           ""
-- jump2View                        string                           ""

return {
	[1] = {
		index = 1,
		cfgId = 1,
		unlockLevel = 3,
		level = 1,
		name = "train soldiers count",
		targetValue = 1,
		targetCfgId = nil,
		showStar = 1,
		totalStar = 3,
		nextIndex = 2,
		reward = {
			[1] = {
				[1] = 101,
				[2] = 300,
			},
		},
		desc = "train soldiers count",
		jump2View = "",
	},
	[2] = {
		index = 2,
		cfgId = 1,
		unlockLevel = 3,
		level = 1,
		name = "train soldiers count",
		targetValue = 1,
		targetCfgId = nil,
		showStar = 2,
		totalStar = 3,
		nextIndex = 3,
		reward = {
			[1] = {
				[1] = 102,
				[2] = 300,
			},
		},
		desc = "train soldiers count",
		jump2View = "",
	},
	[3] = {
		index = 3,
		cfgId = 1,
		unlockLevel = 3,
		level = 1,
		name = "train soldiers count",
		targetValue = 1,
		targetCfgId = nil,
		showStar = 3,
		totalStar = 3,
		nextIndex = 0,
		reward = {
			[1] = {
				[1] = 102,
				[2] = 300,
			},
		},
		desc = "train soldiers count",
		jump2View = "",
	},
	[4] = {
		index = 4,
		cfgId = 2,
		unlockLevel = 3,
		level = 1,
		name = "operate speed count",
		targetValue = 1,
		targetCfgId = nil,
		showStar = 1,
		totalStar = 3,
		nextIndex = 5,
		reward = {
			[1] = {
				[1] = 101,
				[2] = 300,
			},
		},
		desc = "operate speed count",
		jump2View = "",
	},
	[5] = {
		index = 5,
		cfgId = 2,
		unlockLevel = 3,
		level = 1,
		name = "operate speed count",
		targetValue = 1,
		targetCfgId = nil,
		showStar = 2,
		totalStar = 3,
		nextIndex = 6,
		reward = {
			[1] = {
				[1] = 102,
				[2] = 300,
			},
		},
		desc = "operate speed count",
		jump2View = "",
	},
	[6] = {
		index = 6,
		cfgId = 2,
		unlockLevel = 3,
		level = 1,
		name = "operate speed count",
		targetValue = 1,
		targetCfgId = nil,
		showStar = 3,
		totalStar = 3,
		nextIndex = 0,
		reward = {
			[1] = {
				[1] = 102,
				[2] = 300,
			},
		},
		desc = "operate speed count",
		jump2View = "",
	},
	[7] = {
		index = 7,
		cfgId = 1,
		unlockLevel = 3,
		level = 2,
		name = "train soldiers count",
		targetValue = 1,
		targetCfgId = nil,
		showStar = 1,
		totalStar = 3,
		nextIndex = 2,
		reward = {
			[1] = {
				[1] = 101,
				[2] = 300,
			},
		},
		desc = "train soldiers count",
		jump2View = "",
	},
	[8] = {
		index = 8,
		cfgId = 1,
		unlockLevel = 3,
		level = 2,
		name = "train soldiers count",
		targetValue = 1,
		targetCfgId = nil,
		showStar = 2,
		totalStar = 3,
		nextIndex = 3,
		reward = {
			[1] = {
				[1] = 102,
				[2] = 300,
			},
		},
		desc = "train soldiers count",
		jump2View = "",
	},
	[9] = {
		index = 9,
		cfgId = 1,
		unlockLevel = 3,
		level = 2,
		name = "train soldiers count",
		targetValue = 1,
		targetCfgId = nil,
		showStar = 3,
		totalStar = 3,
		nextIndex = 0,
		reward = {
			[1] = {
				[1] = 102,
				[2] = 300,
			},
		},
		desc = "train soldiers count",
		jump2View = "",
	},
	[10] = {
		index = 10,
		cfgId = 2,
		unlockLevel = 3,
		level = 2,
		name = "operate speed count",
		targetValue = 1,
		targetCfgId = nil,
		showStar = 1,
		totalStar = 3,
		nextIndex = 5,
		reward = {
			[1] = {
				[1] = 101,
				[2] = 300,
			},
		},
		desc = "operate speed count",
		jump2View = "",
	},
	[11] = {
		index = 11,
		cfgId = 2,
		unlockLevel = 3,
		level = 2,
		name = "operate speed count",
		targetValue = 1,
		targetCfgId = nil,
		showStar = 2,
		totalStar = 3,
		nextIndex = 6,
		reward = {
			[1] = {
				[1] = 102,
				[2] = 300,
			},
		},
		desc = "operate speed count",
		jump2View = "",
	},
	[12] = {
		index = 12,
		cfgId = 2,
		unlockLevel = 3,
		level = 2,
		name = "operate speed count",
		targetValue = 1,
		targetCfgId = nil,
		showStar = 3,
		totalStar = 3,
		nextIndex = 0,
		reward = {
			[1] = {
				[1] = 102,
				[2] = 300,
			},
		},
		desc = "operate speed count",
		jump2View = "",
	},
	[13] = {
		index = 13,
		cfgId = 1,
		unlockLevel = 3,
		level = 3,
		name = "train soldiers count",
		targetValue = 1,
		targetCfgId = nil,
		showStar = 1,
		totalStar = 3,
		nextIndex = 2,
		reward = {
			[1] = {
				[1] = 101,
				[2] = 300,
			},
		},
		desc = "train soldiers count",
		jump2View = "",
	},
	[14] = {
		index = 14,
		cfgId = 1,
		unlockLevel = 3,
		level = 3,
		name = "train soldiers count",
		targetValue = 1,
		targetCfgId = nil,
		showStar = 2,
		totalStar = 3,
		nextIndex = 3,
		reward = {
			[1] = {
				[1] = 102,
				[2] = 300,
			},
		},
		desc = "train soldiers count",
		jump2View = "",
	},
	[15] = {
		index = 15,
		cfgId = 1,
		unlockLevel = 3,
		level = 3,
		name = "train soldiers count",
		targetValue = 1,
		targetCfgId = nil,
		showStar = 3,
		totalStar = 3,
		nextIndex = 0,
		reward = {
			[1] = {
				[1] = 102,
				[2] = 300,
			},
		},
		desc = "train soldiers count",
		jump2View = "",
	},
	[16] = {
		index = 16,
		cfgId = 2,
		unlockLevel = 3,
		level = 3,
		name = "operate speed count",
		targetValue = 1,
		targetCfgId = nil,
		showStar = 1,
		totalStar = 3,
		nextIndex = 5,
		reward = {
			[1] = {
				[1] = 101,
				[2] = 300,
			},
		},
		desc = "operate speed count",
		jump2View = "",
	},
	[17] = {
		index = 17,
		cfgId = 2,
		unlockLevel = 3,
		level = 3,
		name = "operate speed count",
		targetValue = 1,
		targetCfgId = nil,
		showStar = 2,
		totalStar = 3,
		nextIndex = 6,
		reward = {
			[1] = {
				[1] = 102,
				[2] = 300,
			},
		},
		desc = "operate speed count",
		jump2View = "",
	},
	[18] = {
		index = 18,
		cfgId = 2,
		unlockLevel = 3,
		level = 3,
		name = "operate speed count",
		targetValue = 1,
		targetCfgId = nil,
		showStar = 3,
		totalStar = 3,
		nextIndex = 0,
		reward = {
			[1] = {
				[1] = 102,
				[2] = 300,
			},
		},
		desc = "operate speed count",
		jump2View = "",
	},
	[19] = {
		index = 19,
		cfgId = 1,
		unlockLevel = 3,
		level = 4,
		name = "train soldiers count",
		targetValue = 1,
		targetCfgId = nil,
		showStar = 1,
		totalStar = 3,
		nextIndex = 2,
		reward = {
			[1] = {
				[1] = 101,
				[2] = 300,
			},
		},
		desc = "train soldiers count",
		jump2View = "",
	},
	[20] = {
		index = 20,
		cfgId = 1,
		unlockLevel = 3,
		level = 4,
		name = "train soldiers count",
		targetValue = 1,
		targetCfgId = nil,
		showStar = 2,
		totalStar = 3,
		nextIndex = 3,
		reward = {
			[1] = {
				[1] = 102,
				[2] = 300,
			},
		},
		desc = "train soldiers count",
		jump2View = "",
	},
	[21] = {
		index = 21,
		cfgId = 1,
		unlockLevel = 3,
		level = 4,
		name = "train soldiers count",
		targetValue = 1,
		targetCfgId = nil,
		showStar = 3,
		totalStar = 3,
		nextIndex = 0,
		reward = {
			[1] = {
				[1] = 102,
				[2] = 300,
			},
		},
		desc = "train soldiers count",
		jump2View = "",
	},
	[22] = {
		index = 22,
		cfgId = 2,
		unlockLevel = 3,
		level = 4,
		name = "operate speed count",
		targetValue = 1,
		targetCfgId = nil,
		showStar = 1,
		totalStar = 3,
		nextIndex = 5,
		reward = {
			[1] = {
				[1] = 101,
				[2] = 300,
			},
		},
		desc = "operate speed count",
		jump2View = "",
	},
	[23] = {
		index = 23,
		cfgId = 2,
		unlockLevel = 3,
		level = 4,
		name = "operate speed count",
		targetValue = 1,
		targetCfgId = nil,
		showStar = 2,
		totalStar = 3,
		nextIndex = 6,
		reward = {
			[1] = {
				[1] = 102,
				[2] = 300,
			},
		},
		desc = "operate speed count",
		jump2View = "",
	},
	[24] = {
		index = 24,
		cfgId = 2,
		unlockLevel = 3,
		level = 4,
		name = "operate speed count",
		targetValue = 1,
		targetCfgId = nil,
		showStar = 3,
		totalStar = 3,
		nextIndex = 0,
		reward = {
			[1] = {
				[1] = 102,
				[2] = 300,
			},
		},
		desc = "operate speed count",
		jump2View = "",
	},
	[25] = {
		index = 25,
		cfgId = 1,
		unlockLevel = 3,
		level = 5,
		name = "train soldiers count",
		targetValue = 1,
		targetCfgId = nil,
		showStar = 1,
		totalStar = 3,
		nextIndex = 2,
		reward = {
			[1] = {
				[1] = 101,
				[2] = 300,
			},
		},
		desc = "train soldiers count",
		jump2View = "",
	},
	[26] = {
		index = 26,
		cfgId = 1,
		unlockLevel = 3,
		level = 5,
		name = "train soldiers count",
		targetValue = 1,
		targetCfgId = nil,
		showStar = 2,
		totalStar = 3,
		nextIndex = 3,
		reward = {
			[1] = {
				[1] = 102,
				[2] = 300,
			},
		},
		desc = "train soldiers count",
		jump2View = "",
	},
	[27] = {
		index = 27,
		cfgId = 1,
		unlockLevel = 3,
		level = 5,
		name = "train soldiers count",
		targetValue = 1,
		targetCfgId = nil,
		showStar = 3,
		totalStar = 3,
		nextIndex = 0,
		reward = {
			[1] = {
				[1] = 102,
				[2] = 300,
			},
		},
		desc = "train soldiers count",
		jump2View = "",
	},
	[28] = {
		index = 28,
		cfgId = 2,
		unlockLevel = 3,
		level = 5,
		name = "operate speed count",
		targetValue = 1,
		targetCfgId = nil,
		showStar = 1,
		totalStar = 3,
		nextIndex = 5,
		reward = {
			[1] = {
				[1] = 101,
				[2] = 300,
			},
		},
		desc = "operate speed count",
		jump2View = "",
	},
	[29] = {
		index = 29,
		cfgId = 2,
		unlockLevel = 3,
		level = 5,
		name = "operate speed count",
		targetValue = 1,
		targetCfgId = nil,
		showStar = 2,
		totalStar = 3,
		nextIndex = 6,
		reward = {
			[1] = {
				[1] = 102,
				[2] = 300,
			},
		},
		desc = "operate speed count",
		jump2View = "",
	},
	[30] = {
		index = 30,
		cfgId = 2,
		unlockLevel = 3,
		level = 5,
		name = "operate speed count",
		targetValue = 1,
		targetCfgId = nil,
		showStar = 3,
		totalStar = 3,
		nextIndex = 0,
		reward = {
			[1] = {
				[1] = 102,
				[2] = 300,
			},
		},
		desc = "operate speed count",
		jump2View = "",
	},
	[31] = {
		index = 31,
		cfgId = 1,
		unlockLevel = 3,
		level = 6,
		name = "train soldiers count",
		targetValue = 1,
		targetCfgId = nil,
		showStar = 1,
		totalStar = 3,
		nextIndex = 2,
		reward = {
			[1] = {
				[1] = 101,
				[2] = 300,
			},
		},
		desc = "train soldiers count",
		jump2View = "",
	},
	[32] = {
		index = 32,
		cfgId = 1,
		unlockLevel = 3,
		level = 6,
		name = "train soldiers count",
		targetValue = 1,
		targetCfgId = nil,
		showStar = 2,
		totalStar = 3,
		nextIndex = 3,
		reward = {
			[1] = {
				[1] = 102,
				[2] = 300,
			},
		},
		desc = "train soldiers count",
		jump2View = "",
	},
	[33] = {
		index = 33,
		cfgId = 1,
		unlockLevel = 3,
		level = 6,
		name = "train soldiers count",
		targetValue = 1,
		targetCfgId = nil,
		showStar = 3,
		totalStar = 3,
		nextIndex = 0,
		reward = {
			[1] = {
				[1] = 102,
				[2] = 300,
			},
		},
		desc = "train soldiers count",
		jump2View = "",
	},
	[34] = {
		index = 34,
		cfgId = 2,
		unlockLevel = 3,
		level = 6,
		name = "operate speed count",
		targetValue = 1,
		targetCfgId = nil,
		showStar = 1,
		totalStar = 3,
		nextIndex = 5,
		reward = {
			[1] = {
				[1] = 101,
				[2] = 300,
			},
		},
		desc = "operate speed count",
		jump2View = "",
	},
	[35] = {
		index = 35,
		cfgId = 2,
		unlockLevel = 3,
		level = 6,
		name = "operate speed count",
		targetValue = 1,
		targetCfgId = nil,
		showStar = 2,
		totalStar = 3,
		nextIndex = 6,
		reward = {
			[1] = {
				[1] = 102,
				[2] = 300,
			},
		},
		desc = "operate speed count",
		jump2View = "",
	},
	[36] = {
		index = 36,
		cfgId = 2,
		unlockLevel = 3,
		level = 6,
		name = "operate speed count",
		targetValue = 1,
		targetCfgId = nil,
		showStar = 3,
		totalStar = 3,
		nextIndex = 0,
		reward = {
			[1] = {
				[1] = 102,
				[2] = 300,
			},
		},
		desc = "operate speed count",
		jump2View = "",
	},
	[37] = {
		index = 37,
		cfgId = 1,
		unlockLevel = 3,
		level = 7,
		name = "train soldiers count",
		targetValue = 1,
		targetCfgId = nil,
		showStar = 1,
		totalStar = 3,
		nextIndex = 2,
		reward = {
			[1] = {
				[1] = 101,
				[2] = 300,
			},
		},
		desc = "train soldiers count",
		jump2View = "",
	},
	[38] = {
		index = 38,
		cfgId = 1,
		unlockLevel = 3,
		level = 7,
		name = "train soldiers count",
		targetValue = 1,
		targetCfgId = nil,
		showStar = 2,
		totalStar = 3,
		nextIndex = 3,
		reward = {
			[1] = {
				[1] = 102,
				[2] = 300,
			},
		},
		desc = "train soldiers count",
		jump2View = "",
	},
	[39] = {
		index = 39,
		cfgId = 1,
		unlockLevel = 3,
		level = 7,
		name = "train soldiers count",
		targetValue = 1,
		targetCfgId = nil,
		showStar = 3,
		totalStar = 3,
		nextIndex = 0,
		reward = {
			[1] = {
				[1] = 102,
				[2] = 300,
			},
		},
		desc = "train soldiers count",
		jump2View = "",
	},
	[40] = {
		index = 40,
		cfgId = 2,
		unlockLevel = 3,
		level = 7,
		name = "operate speed count",
		targetValue = 1,
		targetCfgId = nil,
		showStar = 1,
		totalStar = 3,
		nextIndex = 5,
		reward = {
			[1] = {
				[1] = 101,
				[2] = 300,
			},
		},
		desc = "operate speed count",
		jump2View = "",
	},
	[41] = {
		index = 41,
		cfgId = 2,
		unlockLevel = 3,
		level = 7,
		name = "operate speed count",
		targetValue = 1,
		targetCfgId = nil,
		showStar = 2,
		totalStar = 3,
		nextIndex = 6,
		reward = {
			[1] = {
				[1] = 102,
				[2] = 300,
			},
		},
		desc = "operate speed count",
		jump2View = "",
	},
	[42] = {
		index = 42,
		cfgId = 2,
		unlockLevel = 3,
		level = 7,
		name = "operate speed count",
		targetValue = 1,
		targetCfgId = nil,
		showStar = 3,
		totalStar = 3,
		nextIndex = 0,
		reward = {
			[1] = {
				[1] = 102,
				[2] = 300,
			},
		},
		desc = "operate speed count",
		jump2View = "",
	},
	[43] = {
		index = 43,
		cfgId = 1,
		unlockLevel = 3,
		level = 8,
		name = "train soldiers count",
		targetValue = 1,
		targetCfgId = nil,
		showStar = 1,
		totalStar = 3,
		nextIndex = 2,
		reward = {
			[1] = {
				[1] = 101,
				[2] = 300,
			},
		},
		desc = "train soldiers count",
		jump2View = "",
	},
	[44] = {
		index = 44,
		cfgId = 1,
		unlockLevel = 3,
		level = 8,
		name = "train soldiers count",
		targetValue = 1,
		targetCfgId = nil,
		showStar = 2,
		totalStar = 3,
		nextIndex = 3,
		reward = {
			[1] = {
				[1] = 102,
				[2] = 300,
			},
		},
		desc = "train soldiers count",
		jump2View = "",
	},
	[45] = {
		index = 45,
		cfgId = 1,
		unlockLevel = 3,
		level = 8,
		name = "train soldiers count",
		targetValue = 1,
		targetCfgId = nil,
		showStar = 3,
		totalStar = 3,
		nextIndex = 0,
		reward = {
			[1] = {
				[1] = 102,
				[2] = 300,
			},
		},
		desc = "train soldiers count",
		jump2View = "",
	},
	[46] = {
		index = 46,
		cfgId = 2,
		unlockLevel = 3,
		level = 8,
		name = "operate speed count",
		targetValue = 1,
		targetCfgId = nil,
		showStar = 1,
		totalStar = 3,
		nextIndex = 5,
		reward = {
			[1] = {
				[1] = 101,
				[2] = 300,
			},
		},
		desc = "operate speed count",
		jump2View = "",
	},
	[47] = {
		index = 47,
		cfgId = 2,
		unlockLevel = 3,
		level = 8,
		name = "operate speed count",
		targetValue = 1,
		targetCfgId = nil,
		showStar = 2,
		totalStar = 3,
		nextIndex = 6,
		reward = {
			[1] = {
				[1] = 102,
				[2] = 300,
			},
		},
		desc = "operate speed count",
		jump2View = "",
	},
	[48] = {
		index = 48,
		cfgId = 2,
		unlockLevel = 3,
		level = 8,
		name = "operate speed count",
		targetValue = 1,
		targetCfgId = nil,
		showStar = 3,
		totalStar = 3,
		nextIndex = 0,
		reward = {
			[1] = {
				[1] = 102,
				[2] = 300,
			},
		},
		desc = "operate speed count",
		jump2View = "",
	},
	[49] = {
		index = 49,
		cfgId = 1,
		unlockLevel = 3,
		level = 9,
		name = "train soldiers count",
		targetValue = 1,
		targetCfgId = nil,
		showStar = 1,
		totalStar = 3,
		nextIndex = 2,
		reward = {
			[1] = {
				[1] = 101,
				[2] = 300,
			},
		},
		desc = "train soldiers count",
		jump2View = "",
	},
	[50] = {
		index = 50,
		cfgId = 1,
		unlockLevel = 3,
		level = 9,
		name = "train soldiers count",
		targetValue = 1,
		targetCfgId = nil,
		showStar = 2,
		totalStar = 3,
		nextIndex = 3,
		reward = {
			[1] = {
				[1] = 102,
				[2] = 300,
			},
		},
		desc = "train soldiers count",
		jump2View = "",
	},
	[51] = {
		index = 51,
		cfgId = 1,
		unlockLevel = 3,
		level = 9,
		name = "train soldiers count",
		targetValue = 1,
		targetCfgId = nil,
		showStar = 3,
		totalStar = 3,
		nextIndex = 0,
		reward = {
			[1] = {
				[1] = 102,
				[2] = 300,
			},
		},
		desc = "train soldiers count",
		jump2View = "",
	},
	[52] = {
		index = 52,
		cfgId = 2,
		unlockLevel = 3,
		level = 9,
		name = "operate speed count",
		targetValue = 1,
		targetCfgId = nil,
		showStar = 1,
		totalStar = 3,
		nextIndex = 5,
		reward = {
			[1] = {
				[1] = 101,
				[2] = 300,
			},
		},
		desc = "operate speed count",
		jump2View = "",
	},
	[53] = {
		index = 53,
		cfgId = 2,
		unlockLevel = 3,
		level = 9,
		name = "operate speed count",
		targetValue = 1,
		targetCfgId = nil,
		showStar = 2,
		totalStar = 3,
		nextIndex = 6,
		reward = {
			[1] = {
				[1] = 102,
				[2] = 300,
			},
		},
		desc = "operate speed count",
		jump2View = "",
	},
	[54] = {
		index = 54,
		cfgId = 2,
		unlockLevel = 3,
		level = 9,
		name = "operate speed count",
		targetValue = 1,
		targetCfgId = nil,
		showStar = 3,
		totalStar = 3,
		nextIndex = 0,
		reward = {
			[1] = {
				[1] = 102,
				[2] = 300,
			},
		},
		desc = "operate speed count",
		jump2View = "",
	},
	[55] = {
		index = 55,
		cfgId = 1,
		unlockLevel = 3,
		level = 10,
		name = "train soldiers count",
		targetValue = 1,
		targetCfgId = nil,
		showStar = 1,
		totalStar = 3,
		nextIndex = 2,
		reward = {
			[1] = {
				[1] = 101,
				[2] = 300,
			},
		},
		desc = "train soldiers count",
		jump2View = "",
	},
	[56] = {
		index = 56,
		cfgId = 1,
		unlockLevel = 3,
		level = 10,
		name = "train soldiers count",
		targetValue = 1,
		targetCfgId = nil,
		showStar = 2,
		totalStar = 3,
		nextIndex = 3,
		reward = {
			[1] = {
				[1] = 102,
				[2] = 300,
			},
		},
		desc = "train soldiers count",
		jump2View = "",
	},
	[57] = {
		index = 57,
		cfgId = 1,
		unlockLevel = 3,
		level = 10,
		name = "train soldiers count",
		targetValue = 1,
		targetCfgId = nil,
		showStar = 3,
		totalStar = 3,
		nextIndex = 0,
		reward = {
			[1] = {
				[1] = 102,
				[2] = 300,
			},
		},
		desc = "train soldiers count",
		jump2View = "",
	},
	[58] = {
		index = 58,
		cfgId = 2,
		unlockLevel = 3,
		level = 10,
		name = "operate speed count",
		targetValue = 1,
		targetCfgId = nil,
		showStar = 1,
		totalStar = 3,
		nextIndex = 5,
		reward = {
			[1] = {
				[1] = 101,
				[2] = 300,
			},
		},
		desc = "operate speed count",
		jump2View = "",
	},
	[59] = {
		index = 59,
		cfgId = 2,
		unlockLevel = 3,
		level = 10,
		name = "operate speed count",
		targetValue = 1,
		targetCfgId = nil,
		showStar = 2,
		totalStar = 3,
		nextIndex = 6,
		reward = {
			[1] = {
				[1] = 102,
				[2] = 300,
			},
		},
		desc = "operate speed count",
		jump2View = "",
	},
	[60] = {
		index = 60,
		cfgId = 2,
		unlockLevel = 3,
		level = 10,
		name = "operate speed count",
		targetValue = 1,
		targetCfgId = nil,
		showStar = 3,
		totalStar = 3,
		nextIndex = 0,
		reward = {
			[1] = {
				[1] = 102,
				[2] = 300,
			},
		},
		desc = "operate speed count",
		jump2View = "",
	},
}
