-- cfgId                            int                              ""ID
-- minMit                           int                              ""vip""mit
-- maxMit                           int                              ""vip""mit
-- starCoinRatio                    float                            ""
-- iceRatio                         float                            ""
-- titaniumRatio                    float                            ""
-- gasRatio                         float                            ""
-- hydroxylAddition                 int                              PVP""
-- battleNumAdd                     int                              ""PVP""
-- buildQueue                       int                              ""
-- withdrawReduce                   int                              VIP""cd
-- productId                        string                           ""
-- duration                         int                              ""
-- gridPlayerMax                    int                              ""

return {
	[0] = {
		cfgId = 0,
		minMit = 0,
		maxMit = 199999,
		starCoinRatio = 0,
		iceRatio = 0,
		titaniumRatio = 0,
		gasRatio = 0,
		hydroxylAddition = 0,
		battleNumAdd = 0,
		buildQueue = 0,
		withdrawReduce = 0,
		productId = "0",
		duration = 0,
		gridPlayerMax = 15,
	},
	[1] = {
		cfgId = 1,
		minMit = 200000,
		maxMit = 499999,
		starCoinRatio = 0,
		iceRatio = 0,
		titaniumRatio = 0,
		gasRatio = 0,
		hydroxylAddition = 4000,
		battleNumAdd = 1,
		buildQueue = 0,
		withdrawReduce = 0,
		productId = "gb.vip.6",
		duration = 30,
		gridPlayerMax = 15,
	},
	[2] = {
		cfgId = 2,
		minMit = 500000,
		maxMit = 999999,
		starCoinRatio = 0,
		iceRatio = 0,
		titaniumRatio = 0,
		gasRatio = 0,
		hydroxylAddition = 10000,
		battleNumAdd = 1,
		buildQueue = 0,
		withdrawReduce = 864000,
		productId = "gb.vip.15",
		duration = 30,
		gridPlayerMax = 20,
	},
	[3] = {
		cfgId = 3,
		minMit = 1000000,
		maxMit = 1699999,
		starCoinRatio = 0,
		iceRatio = 0,
		titaniumRatio = 0,
		gasRatio = 0,
		hydroxylAddition = 18000,
		battleNumAdd = 2,
		buildQueue = 0,
		withdrawReduce = 864000,
		productId = "gb.vip.30",
		duration = 30,
		gridPlayerMax = 20,
	},
	[4] = {
		cfgId = 4,
		minMit = 1700000,
		maxMit = 2599999,
		starCoinRatio = 0,
		iceRatio = 0,
		titaniumRatio = 0,
		gasRatio = 0,
		hydroxylAddition = 34000,
		battleNumAdd = 2,
		buildQueue = 0,
		withdrawReduce = 1728000,
		productId = "gb.vip.50",
		duration = 30,
		gridPlayerMax = 25,
	},
	[5] = {
		cfgId = 5,
		minMit = 2600000,
		maxMit = 3699999,
		starCoinRatio = 0,
		iceRatio = 0,
		titaniumRatio = 0,
		gasRatio = 0,
		hydroxylAddition = 54000,
		battleNumAdd = 3,
		buildQueue = 0,
		withdrawReduce = 1728000,
		productId = "gb.vip.80",
		duration = 30,
		gridPlayerMax = 30,
	},
	[6] = {
		cfgId = 6,
		minMit = 3700000,
		maxMit = 4999999,
		starCoinRatio = 0,
		iceRatio = 0,
		titaniumRatio = 0,
		gasRatio = 0,
		hydroxylAddition = 78000,
		battleNumAdd = 3,
		buildQueue = 0,
		withdrawReduce = 1728000,
		productId = "gb.vip.110",
		duration = 30,
		gridPlayerMax = 30,
	},
	[7] = {
		cfgId = 7,
		minMit = 5000000,
		maxMit = 6499999,
		starCoinRatio = 0,
		iceRatio = 0,
		titaniumRatio = 0,
		gasRatio = 0,
		hydroxylAddition = 108000,
		battleNumAdd = 3,
		buildQueue = 1,
		withdrawReduce = 1728000,
		productId = "gb.vip.150",
		duration = 30,
		gridPlayerMax = 30,
	},
	[8] = {
		cfgId = 8,
		minMit = 6500000,
		maxMit = 8199999,
		starCoinRatio = 0,
		iceRatio = 0,
		titaniumRatio = 0,
		gasRatio = 0,
		hydroxylAddition = 144000,
		battleNumAdd = 3,
		buildQueue = 1,
		withdrawReduce = 1728000,
		productId = "gb.vip.200",
		duration = 30,
		gridPlayerMax = 40,
	},
	[9] = {
		cfgId = 9,
		minMit = 8200000,
		maxMit = -1,
		starCoinRatio = 0,
		iceRatio = 0,
		titaniumRatio = 0,
		gasRatio = 0,
		hydroxylAddition = 186000,
		battleNumAdd = 4,
		buildQueue = 1,
		withdrawReduce = 1728000,
		productId = "gb.vip.250",
		duration = 30,
		gridPlayerMax = 40,
	},
}
