---
- name: include platform specific vars
  include_vars: "{{ansible_os_family}}.yml"
  tags:
      - redis
      - download
      - install

- name: install deps...
  with_items: "{{dep_pkgs}}"
  package:
      name: "{{item}}"
      state: present
  become: yes
  become_user: root
  tags:
      - redis
      - download

- name: download...
  get_url:
      url: "{{redis_tgz_url}}"
      dest: "{{redis_src_parent_dir}}/{{redis_tgz}}"
      checksum : "{{redis_checksum}}"
      mode: 0644
  become: yes
  become_user: root
  tags:
      - redis
      - download

- name: unarchive...
  unarchive:
    remote_src: yes
    src: "{{redis_src_parent_dir}}/{{redis_tgz}}"
    dest: "{{redis_src_parent_dir}}"
    creates: "{{redis_src_dir}}"
  become: yes
  become_user: root
  tags:
      - redis
      - install

- name: build...
  command: make
  args:
    chdir: "{{redis_src_dir}}"
    creates: "{{redis_src_dir}}/src/redis-server"
  become: yes
  become_user: root
  tags:
      - redis
      - install

- name: install...
  command: make install
  args:
    chdir: "{{redis_src_dir}}"
    creates: /usr/local/bin/redis-server
  become: yes
  become_user: root
  tags:
      - redis
      - install
