---
# Variable setup.
- name: Include OS-Specific variables
  include_vars: "{{ ansible_os_family }}.yml"
  tags:
      - jenkins
      - download
      - install

# Setup/install tasks.
- include_tasks: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'
  tags:
      - jenkins
      - download
      - install

- include_tasks: setup-Debian.yml
  when: ansible_os_family == 'Debian'
  tags:
      - jenkins
      - download
      - install
